### ISSUE TITLE
How to get a reference to the container of a SwinjectStoryboard

### ISSUE THREAD

**Issue by mrahmiao** [Swinject/Swinject#103]
I've encountered such a situation that I've got a network service as a view controller's dependency. And a token is required for the network service. The token is fetched after initializing the container. So the network service registered in the container is not correct.

Is there a way to solve such a problem in Swinject?

**Comment by yoichitgy** [comment]
Maybe this???
https://github.com/Swinject/Swinject/blob/v1/Documentation/DIContainer.md#registration-with-arguments-in-a-di-container

**Comment by mrahmiao** [comment]
@yoichitgy All of my component registrations are in the `setup` method  of `SwinjectStoryboard`. Is that possible to use the container outside the method?

**Comment by yoichitgy** [comment]
#27 might be helpful for you.

**Comment by mrahmiao** [comment]
@yoichitgy I was wondering how to get the reference to the container outside the `setup` method such as the `c` in last statement of the code snippets you provided in #27 :

```swift
// Inside setup()
let c = Container()
c.register(ViewModel.self) { r, foo in ViewModel(foo: foo) }
c.registerForStoryboard(ViewController.self) { r, vc in vc.vm = r.resolve(ViewModel.self, arg1: ???) }
c.register(ViewController.self) { r, sb, a1 in
    let vc = sb.instantiateViewControllerWithIdentifier("ViewController")
    vc.vm = r.resolve(ViewModel.self, arg1: a1)
    return vc
}

// Instantiate ViewController
let resolvedVC = c.resolve(ViewController.self, arguments: (sb, arg1))
```

It seems out of scope =.=

**Comment by yoichitgy** [comment]
You can use `create(name:bundle:container:)` method of SwinjectStorybard.
http://cocoadocs.org/docsets/Swinject/1.1.2/Classes/SwinjectStoryboard.html#/s:ZFC8Swinject18SwinjectStoryboard6createFT4nameSS6bundleGSqCSo8NSBundle_9containerPS_19PropertyRetrievableS_10Resolvable__S0_

**Comment by yoichitgy** [comment]
Feel free to reopen this issue if you have more questions about this topic.

**Comment by psi-gh** [comment]
Hello!
@yoichitgy I don't see the solution of OP's problem (I have the same request). 
For example, if I'm using VC'c with dependencies, then I have to use SwinjectStoryboard.
If I'm using SwinjectStoryboard, then I'm probably want to create my own Container and pass it to SwinjectStoryboard (either way I don't know how to pass another dependencies in unit tests where I can simply create another Container with mocks). 
So I have to register all the stuff (ViewController, ViewModels, my various Services such as "Rest Api Controller Service", etc.) in this container which im passing to SwincjectStoryboard.
And my problem is: when I wan't to resolve one of my dependency (such as some service) in some place of code which is NOT ViewController created in SB, how can I get Resolver instance to resolve some dependency? Now I can only type `SwinjectStoryboard.defaultContainer` but what to do if I'm using my own container?
I can create container, save ref to it im my app (in some singleton class) and then pass this container to SwinjectStoryboard. But it seems to strange for me if I can't get current container from SwinjectStoryboard class.

I hope my message it's not too messy :) Thanks.
