### ISSUE TITLE
Ambiguous reference to member 'register(_:name:factory:) Error

### ISSUE THREAD

**Issue by jsaguiar** [Swinject/Swinject#107]
When I try to load my ViewController, I want to inject my ViewModel that have some arguments.
Something like:

``` swift
container.register(ViewModel.self) { r, string1, string2 in
    ViewModel(string1: string1, string2: string2, api: r.resolve(APIProtocol.self)!)
}
container.register(ViewController.self) { r, string1, string2 in
    ViewController(viewModel: r.resolve(ViewModel.self, arguments: (string1, string2))!)
}
```

But I got this error

```
 Ambiguous reference to member 'register(_:name:factory:)
```

**Comment by jakubvano** [comment]
Likely the problem is, that compiler is unable to infer types of `string1` and `string2` parameters in

```
container.register(ViewController.self) { r, string1, string2 in
    ViewController(viewModel: r.resolve(ViewModel.self, arguments: (string1, string2))!)
}
```

Changing it to

```
container.register(ViewController.self) { (r, string1: String, string2: String) in
    ViewController(viewModel: r.resolve(ViewModel.self, arguments: (string1, string2))!)
}
```
should help.

**Comment by yoichitgy** [comment]
Thanks @jakubvano for the exact answer!

**Comment by jsaguiar** [comment]
thanks @jakubvano.

**Comment by igordeoliveirasa** [comment]
please, help me guys? What is wrong here: 

> 
defaultContainer.register(APIModel.self, name:"FileAPI") { r in
            return APIModel(routeName: "files", api: r.resolve(AuthenticationAPI.self), defaultAPIVersion: "v3")
        }
>

**Comment by igordeoliveirasa** [comment]
i'm getting the same error message you had.

**Comment by jsaguiar** [comment]
I am using 1.1.2 version, try it, it may solve your problem for now. @igordeoliveirasa

**Comment by jakubvano** [comment]
@igordeoliveirasa I've noticed you are not unwrapping optional `r.resolve(AuthenticationAPI.self)` - is your constructor accepting `AuthenticationAPI?`? If not than changing it to `r.resolve(AuthenticationAPI.self)!` might solve your issue.

**Comment by ened** [comment]
@jsaguiar We should update the docs in https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#registration-with-arguments-to-di-container


Reopen until added?

**Comment by jakubvano** [comment]
@ened There is a (remark)[https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#remark] expliciltly warning to use exact argument types, also in current version there is log output highlighting exact reason for resolution failure.

However I can see that - especially to newcomers -  it may not be clear that e.g. `String`, `String!` and `String?` are all different types. Feel free to make a PR extending Remark section with this distinction 😉

**Comment by jakubvano** [comment]
@ened There is a (remark)[https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#remark] section explicitly warning about using the exact argument types. Also, in current version there is a log output clarifying reason for resolution failure, which should help debugging these types of issues.

I can see that e.g. `String`, `String?` and `String!` being different types may not be clear - especially to Swift newcomers. Feel free to make PR extending the `remark` section with this distinction 😉

**Comment by yoichitgy** [comment]
Updated the doc as commit 65b7851590b168108b1f4d17dc0bec5c16e5e5ee.

**Comment by codenameDuchess** [comment]
Just a quick comment for anyone else who runs across this issue .... the label is "argument" not "arguments" when you're resolving.  Took me a while to figure it out, hopefully will save someone else the time.

container.register(ViewController.self) { (r, string1: String, string2: String) in
    ViewController(viewModel: r.resolve(ViewModel.self, argument: (string1, string2))!)
}
