### ISSUE TITLE
On injecting Class instances

### ISSUE THREAD

**Issue by josephbeuysmum** [Swinject/Swinject#11]
Hi Yoichi. This isn't an issue, I just wanted to get your attention to see if you were able to answer this question on StackOverflow: 

http://stackoverflow.com/questions/33010757/using-swinject-to-inject-a-model-class-instance-into-a-view-class-instance-in-sw

**Comment by yoichitgy** [comment]
I answered to the question in [StackOverflow](http://stackoverflow.com/questions/33010757/using-swinject-to-inject-a-model-class-instance-into-a-view-class-instance-in-sw). Thank you for asking the question there because a general question is more discoverable in StackOverflow than GitHub Issues.

**Comment by josephbeuysmum** [comment]
Yoichi, thank you. I have made changes along the lines of your suggestion but I am still getting nowhere. I have edited the question to 1. make it clearer; and 2. include your suggestion, but I am still not succeeding. If possible, could you look again please and suggest changes? Thank you, JBM.

**Comment by yoichitgy** [comment]
Updated [my answer in StackOverflow](http://stackoverflow.com/questions/33010757/using-swinject-to-inject-a-model-class-instance-into-a-view-class-instance-in-sw). Also added Issue #12 to Swinject project. Thank you for asking the question. I can prioritize what new feature should be implemented next.

**Comment by josephbeuysmum** [comment]
Thanks Yoichi, have managed to get my test project running, thank you for helping out, and thank you for being patient with my stupid, badly researched questions, very nice of you. It's also nice to have the first Swinject question on StackOverflow. As we both said, would be good to get an actual Swinject tag over there. JBM.

**Comment by yoichitgy** [comment]
Swinject version 0.3 supports the implicit instantiation from "Main" storyboard.
