### ISSUE TITLE
How can I pass in a delegate as an argument of the resolve method

### ISSUE THREAD

**Issue by matthewswallace** [Swinject/Swinject#110]
I have a class registered with a SwinjectStoryboard+Setup file. I'd like to pass an argument when I resolve the class so that I can pass a delegate to the constructor of the class before swinject passes it back to me. 

I created a stackoverflow question about this. I get an error when trying to pass this to the resolve method and I'm not sure why. 

http://stackoverflow.com/questions/37767606/how-do-i-pass-arguments-to-the-resolve-method-when-using-swinject?stw=2

**Comment by yoichitgy** [comment]
Closing this issue because I answered in the Stackoverflow's thread.

**Comment by matthewswallace** [comment]
This was not answered.

**Comment by yoichitgy** [comment]
Answered again😃
