### ISSUE TITLE
Support Swift 3.0

### ISSUE THREAD

**Issue by thalmicMark** [Swinject/Swinject#112]
What's the timeline for this? We aren't blocked by it yet, but will be in a few months.

**Comment by yoichitgy** [comment]
I tried Xcode 8 with Swift 3, and got a lot of errors to support them. So my current thought is:

- Support Xcode 8 and Swift 3 in `master` branch for Swinject v2 (including betas).
- Do not support them in `v1` branch for Swinject v1 series.

So, it looks good to migrate the code in `master` to Swift 3 first, then the other features for v2 will be implemented.

@thalmicMark, does the plan look good for you?

**Comment by garnett** [comment]
I've made a PR for that: https://github.com/Swinject/Swinject/pull/113

**Comment by yoichitgy** [comment]
Thanks @garnett for the WIP PR. Yes, it looks we have to wait Quick and Nimble.

**Comment by yoichitgy** [comment]
It looks we can support Xcode 8 with Swift 2.3 for Swinject 1.x later with _Use Legacy Swift Language Version_ option.

**Comment by thalmicMark** [comment]
Can we get a version of Swinject that supports Swift 2.3 and is built in Xcode 8? I get the following error when I try to build my Swift 2.3 project in Xcode 8:

    module file was created by an older version of the compiler; rebuild 'Swinject' and try again: 
    <path_to_project>/Frameworks/Swinject.framework/Modules/Swinject.swiftmodule/arm64.swiftmodule

I'm using Swinject v1.1.1.

**Comment by yoichitgy** [comment]
I'll probably release a version supporting Swift 2.3 and Xcode 8 in `v1` branch.

For now, if you use Carthage, please add `--no-use-binaries` option to `carthage update` command.

**Comment by yoichitgy** [comment]
Thanks @garnett for your work on swift3 branch (#113). I merged the branch into master. We go with Xcode 8 beta on master branch to avoid conflicts with new feature implementation.

**Comment by yoichitgy** [comment]
Currently:

- `master` branch supports Swift 3 with Xcode 8 beta 6
- `v1` branch supports Swift 2.2/2.3 with Xcode 7.3.1/8(beta).

**Comment by robinhayward** [comment]
I am using Xcode 8 beta 6 and getting:

Module compiled with Swift 2.3 cannot be imported in Swift 3.0:
...../Carthage/Build/iOS/Swinject.framework/Modules/Swinject.swiftmodule/x86_64.swiftmodule

That is after doing `xcode-select` for the beta and `carthage update --no-use-binaries --platform ios` is this something I am doing wrong or a bug?

**Comment by yoichitgy** [comment]
@robinhayward did you use the latest Carthage?

**Comment by robinhayward** [comment]
@yoichitgy Just updated and tried again, same issue :/

**Comment by yoichitgy** [comment]
Thanks for checking. It looks we need some investigation.

**Comment by yoichitgy** [comment]
I confirmed Carthage v0.18 with Xcode 8 (GM) worked.

**Comment by yoichitgy** [comment]
Swinject [v2.0.0-beta.2](https://github.com/Swinject/Swinject/releases/tag/2.0.0-beta.2) supports Swift 3 and [v1.1.4](https://github.com/Swinject/Swinject/releases/tag/1.1.4) supports Swift 2.3.
