### ISSUE TITLE
Shared Container instance between App and Test targets

### ISSUE THREAD

**Issue by jrmbrgs** [Swinject/Swinject#114]
Hi,

We use Swinject as a DI in our project. It works well, but we still have an issue for Unit Test purpose in case of singleton. 
We noticed, in case of a registered singleton, used both in the App code and in our Unit test code, that the register closure is exec twice, one time is the APP context and one other in the Unit test context.

I'm wondering if there is any solution to share the same Container instance between App and Test code when Tests Target is launched ?

Here is a simple ex. :
 * DI.swift
```Swift
var DI = Container() { c in
    // Register Foo as a singlton
    c.register(Foo.self) { r in
        print("new Foo")
        return Foo()
    }
    .inObjectScope(.Container)
}
```

* App Delegate
```Swift
print("From App")
DI.resolve(Foo.self)!.bar()
```

* Quick & Nimble Unit Test
```Swift
class TestConfiguration: QuickConfiguration {
    override class func configure(configuration: Configuration) {
        print("From UT")
        DI.resolve(Foo.self)!.bar()
    }
}
```

The related console output (among other lines)
```
From App
New Foo
From UT
New Foo
```
While I was expected
```
From App
New Foo
From UT
```

Any Suggestion ?

Thx in advance !

**Comment by jrmbrgs** [comment]
I finally found the issue, which is not related to Swinject, which works as a charm.
My DI file had my test target as "member target" in addition to my App target.

**Comment by yoichitgy** [comment]
Thank you for investigating and sharing the issue👍
