### ISSUE TITLE
SwinjectSimpleExample not building

### ISSUE THREAD

**Issue by x-hovo-x** [Swinject/Swinject#119]
Hi guys,

Just trying to see how Swinject works...
Clone SwinjectSimpleExample from github run pod install and try to build but got error "SwinjectSimpleExample/SwinjectSimpleExample/WeatherFetcher.swift:10:8: No such module 'Alamofire'"
This is not connected only to Alamofire same problem with Swiftyjson and others

Already cleaned build folder, deintegrate pod clean and again installed, changed version(s), nothing helped.

Using xcode 7.3.1
Swift version 2.2

 Regards,
HA

**Comment by yoichitgy** [comment]
I opened an issue in SwinjectSimpleExample project, and am going to close this issue in Swinject project. 

https://github.com/Swinject/SwinjectSimpleExample/issues/1
