### ISSUE TITLE
Support implicit instantiation of UIWindow and its root view controller from "Main" storyboard

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject#12]
Support implicit instantiation of UIWindow and its root view controller from "Main" storyboard.

If the feature is supported, the following cases are perfectly resolved.

- Issue #11
- [StackOverflow question](http://stackoverflow.com/questions/33010757/using-swinject-to-inject-a-model-class-instance-into-a-view-class-instance-in-sw)

**Comment by yoichitgy** [comment]
Implemented as a new feature for version 0.3.

**Comment by josephbeuysmum** [comment]
Nice Yoichi. Will you be adding a code example?

**Comment by yoichitgy** [comment]
Documented [here](https://github.com/Swinject/Swinject/blob/master/Documentation/Storyboard.md) :)

**Comment by josephbeuysmum** [comment]
Very nice Yoichi, thanks.
