### ISSUE TITLE
Cannot build the project (PRODUCT_NAME missing) if it is downloaded as a zip file and xcconfigs is not retrieved by Carthage

### ISSUE THREAD

**Issue by colnaghijr** [Swinject/Swinject#130]
PRODUCT_NAME is undefined so a ⌘+B will fail

This might not be intentional; it's a better experience to download the zip and have it running right away.

Thanks,
--rob

**Comment by yoichitgy** [comment]
@colnaghijr, thanks for submitting the issue. I'll check the problem.

**Comment by yoichitgy** [comment]
@colnaghijr: Which sample project did you mention?

I checked [SwinjectSimpleExample](https://github.com/Swinject/SwinjectSimpleExample) and [SwinjectMVVMExample](https://github.com/Swinject/SwinjectMVVMExample). Both of them have `PRODUCT_NAME` set.

**Comment by yoichitgy** [comment]
I'm going to close this issue because it looks actually ok. @colnaghijr please feel free to reopen this issue point out the exact location of the problem if you still see the issue.

**Comment by ikesyo** [comment]
I assume this is because the zip file downloaded from GitHub does not contains checked out submodules. This project depends on `xcconfigs` submodule, so that should be the cause.

**Comment by yoichitgy** [comment]
Thanks @ikesyo for pointing out the problem😃👍 I am going to check the cause.

**Comment by raphh11** [comment]
I want to use the Sample-iOS Playground but I'm experiencing the same issue when downloading the project from https://github.com/Swinject/Swinject : `Build setting PRODUCT_NAME undefined`.

**Comment by yoichitgy** [comment]
Thanks @raphh11 for your followup comment. I understood the problem correctly.

Some people asked GitHub to add submodules to a zip file years ago, but they still doesn't support submodules in a zip.
http://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download

I'll pick one of the followings as a resolution to this issue:

A. Remove dependency on `xcconfigs` and add xcconfig files to Swinject repo.
B. Just document how to try building Swinject project using `git clone` without downloading a zip file.

**Comment by rcfrias** [comment]
Having same problem here

**Comment by mpdifran** [comment]
I'm noticing this as well. I'm including `SwinjectStoryboard` through Carthage, and the version of `Swinject` that is checked out by `SwinjectStoryboard` is missing the `PRODUCT_NAME`. So it seems that even using Carthage doesn't solve the issue entirely.

**Comment by jakubvano** [comment]
This should be resolved by #258 and #259 - From the downloaded zip I am able to build project, run playground and after `carthage bootstrap` running the tests.

I will close this, feel free to reopen if some related problems still persist.
