### ISSUE TITLE
Auto-registration 

### ISSUE THREAD

**Issue by tkohout** [Swinject/Swinject#132]
Hello, 
first I would like to thank you for this awesome project!

We are using Swinject extensively on our project and are too lazy to write all the code to register our services. I have come up with extension based on generics that makes our life easier:

For my example I have this registration code:

```
container.register(MasterViewModeling.self) { r in
     MasterViewModeling(api: r.resolve(APIServicing.self)!, geocoder: r.resolve(Geocoding.self)!, locationManager: r.resolve(LocationManaging.self)!, detailModelFactory: r.resolve(DetailViewModelFactory.self)!)
}
```

If I extend Resolvable I can use power of generics and custom operator

```
extension Resolvable {
    func resolve<Service>() -> Service? {
       return self.resolve(Service.self)
    }
}
```

```
postfix operator ~ {}
postfix func ~ <Service>(r: ResolverType) -> Service {
    return r.resolve()!
}
```

And my registration can be significantly shorter, given that I resolve nameless services without arguments (which is usually the case):

```
container.register(MasterViewModeling.self) { r in
     MasterViewModeling(api: r~, geocoder: r~, locationManager: r~, detailModelFactory: r~)
}
```

This is significantly shorter, but we can do even more. I took inspiration in [Curry](https://github.com/thoughtbot/Curry) and find out that we can use initializer's type to infere its dependencies. Creating new `register(initializer:service:)` method:

```
func register<Service, A, B, C, D>(initializer initializer: (A, B, C, D) -> Service, service: Service.Type, name: String? = nil) -> ServiceEntry<Service> {
   return self.register(service.self, name: name, factory: { r in 
       initializer(r.resolve()!, r.resolve()!, r.resolve()!, r.resolve()!)
   } as (Resolvable) -> Service)
}
```

We get registration:

```
container.register(initializer: MasterViewModel.init, service: MasterViewModeling.self)
```

This is awesome, because even when I add new dependency I don't have to change my container registration code.

This method have to be generated for every number of dependencies, in a same way as Curry.
See [generated source code](https://github.com/AckeeCZ/Swinject/blob/auto-registration/Sources/AutoRegistration.swift)

 I have written a script that does exactly that, so the number of dependencies can be dynamically changed. (I am not sure if .erb is strong enough to be able to generate it, so I wrote it in swift, see the [script](https://github.com/AckeeCZ/Swinject/blob/auto-registration/bin/generate) )

I also often pass dynamic arguments to my services, but don't want to write the whole register factory. By creating `register(initializer:service:argument:)` method:

```
func resolve<Service, Arg1>(argument argument: (Arg1)) -> Service? {
   return (argument as? Service) ?? self.resolve(Service.self, argument: argument)
}

func register<Service, A, B, C, D, Arg1>(initializer initializer: (A, B, C, D) -> Service, service: Service.Type, name: String? = nil, argument: (Arg1.Type)) -> ServiceEntry<Service> {
   return self.register(service.self, name: name, factory: { r, arg1 in 
       initializer(r.resolve(argument: (arg1))!, r.resolve(argument: (arg1))!, r.resolve(argument: (arg1))!, r.resolve(argument: (arg1))!)
   } as (Resolvable, Arg1) -> Service)
}

```

we can than register like this. The dynamic argument is tested against all dependencies (in runtime) in initializer and if it fits the type it is passed instead of resolving dependency.

```
container.register(initializer: MasterViewModel.init, service: MasterViewModeling.self, argument: MyDynamicArgument.self )
```

This is not compiler safe though, but given that there can be multiple arguments and multiple dependencies on different positions, the number of permutation that would have to be generated is pretty hight. If we would force users to pass dynamic arguments as first and dependencies after them, it could be made compiler safe. But I think it would only lead to confusion. 

Now, there are obviously some drawbacks. If you have two initializers in one class, compiler doesn't know which one to choose. Also if you have two inits in same class hierarchy and they have same number of arguments there will be a conflict. (e.g. `UIViewController(coder: NSCoder)` and `MyViewController(viewModel: ViewModel)`)

You can either create custom named init, and use it for registration:

```
class func swinit(api: APIServicing, geocoder: Geocoding, locationManager: LocationManaging, detailModelFactory: DetailModelingFactory){
	return self.init(....)
}
```

~~Or perform some swift magic and convince compiler to use your init. Sometimes during writing it causes bug in compiler which then runs on 200% CPU, but once written it is ok. You have been warned :P.~~

You can force the compiler to choose specific init. This is probably better option.
```
container.register(initializer: MasterViewModel.init(api:geocoder:locationManager:detailModelFactory:), service: MasterViewModeling.self)
```

Also, if you have an optional dependency in your init, the autoregistration won't work. For the registration:

```
func register<Service, A, B, C, D, Arg1>(initializer initializer: (A, B, C, D)
```

There could be many permutations like (A?, B, C, D), (A?, B?, C, D), (A, B, C, D?) ... which is impossible to generate for more than few dependencies.

And of course, if you have named services, or more complex registration you will have to use current registration factories.

This issue is meant to start discussion whether auto-registration should be part of swinject. On my part, I am pretty happy with the extension, it reduced our container file by a large margin, but we don't use all features of swinject so there might be additional problems.

**Comment by yoichitgy** [comment]
Hello @tkohout! Thank you for the idea😃 I'll read it and reply shortly.

**Comment by jakubvano** [comment]
Hi @tkohout ,

I also find writing all that code around registering services really tedious, however didn't put much thought into reducing it yet. I think that some sort of boilerplate reduction should be part of Swinject, and ideally it should spped up writing the code and (more importantly) improve readability.

Personally, I prefer the "autoregistration" over code generation ([Swinject-CodeGen](https://github.com/Swinject/Swinject-CodeGen)) - it feels more natural and you dont need to add yet another tool to your process. My biggest fear however, is that adding yet more magic might make it incredibly difficult to debug and much harder to adopt.

### Couple of thoughts on actual extension:

 Having `resolve` automatically infer the type was part of [Dip](https://github.com/AliSoftware/Dip) from the beginning, maybe there is something to learn there?


> ```
container.register(initializer: MasterViewModel.init, service: MasterViewModeling.self)
```

I would probably swap the order of arguments to match original `register` method


> You can force the compiler to choose specific init. This is probably better option.

Agreed, creating separate initialiser just for injection purposes makes objects coupled to the DI framework.

**Comment by tkohout** [comment]
Hi @jakubvano ,
the debugging is indeed more difficult, that's why I added [checkResolved](https://github.com/AckeeCZ/Swinject/blob/auto-registration/Sources/AutoRegistration.swift#L689) method to check whether dependency had been resolved and print an assert message. Something in style `Failed to resolve SomeDependency, initializer: (SomeDependency, AnotherDependency) -> MyService`

For your second suggestion, swaping arguments would be nice, unfortunately would it would cause ambiguity for two methods:

container.register(service:initiliazer)
container.register(service:factory)

because they have basically same type signature apart from the name of the second argument.
So trailing closure notation for 
```
register(Service.self) { r in
}
```
would no longer work. So it is either this, or rename the function altogether.

Cheers
Tomas

**Comment by yoichitgy** [comment]
@jakubvano thank you for your comment to get a better discussion👍 @tkohout it's very interesting to read your proposal. I got a lot of learnings from your idea!

### In short:

- I'm positive to add the implicit `resolve<Service>() -> Service?` function to Swinject core repository.
- I'm not confident to add the `~` operator to Swinject repository. It might be good to add it to another extension repository.
- I want to add the other things to another extension repository to avoid showing to many `resolve` methods in an Xcode autocompletion popup (especially for beginner users).

---

I understand some people prefer explicit definitions like [Swinject-CodeGen](https://github.com/Swinject/Swinject-CodeGen) does, and some prefer implicit ones like @tkohout wrote. So having both of them is great for Swinject users. One thing I want to keep is simplicity and easy learning curve for new users because Dependency Injection is still a new or developing concept in iOS field. So, I want to put advanced things to another repository as an extension to Swinject.

### My opinions (might be nitpicks):

In place of `~` operator, `~>` might be good to use as below because it looks like `->`, which is a function returning something (though this operator is just my preference).

```swift
MasterViewModeling(api: r~>, geocoder: r~>, locationManager: r~>, detailModelFactory: r~>)
```

As @jakubvano told, I also think swapping the arguments below looks good because it can be read as "register the service (to be resolved to the component with) the initializer". The current API has that order of parameters. If the swapped one has conflict as you told, it looks good to use another name. If we don't find a good name, we can use the order `register(initializer:service)`.

> ```
container.register(initializer: MasterViewModel.init, service: MasterViewModeling.self)
```

I also think coupling with a specific DI framework is a bad idea.

The `checkResolved` method is nice. I was also thinking to add that kind of method even to the current API for easier debugging. I'll learn from your method to implement the similar one to the current API.

**Comment by yoichitgy** [comment]
@tkohout, @jakubvano: which repository looks good to add `~` (or something like `~>`) operator? Swinject core repository or another extension repository?

**Comment by yoichitgy** [comment]
FYI: I'm planning to move "Extensions" section of README to under "Features" section to promote Swinject extensions.

**Comment by tkohout** [comment]
Hi @yoichitgy!
Glad you like my suggestion.

I agree that adding the autoregistration as an extension would be better for beginner users. I like `~>` operator, it makes more sense than `~`. I think there is no harm in putting the operator to the core repository. I would suggest to add also other operators that we use in our projects, something like [this](https://gist.github.com/tkohout/fcfe34efca2820725845b8b5d61bd62d)

you can then use them followingly:

```
MyService(dependencyA: r ~> DependencyA.self, dependencyB: r ~> DependencyB.self)
MyService(dependencyA: r ~> (DependencyA.self, argument: arg1))
MyService(dependencyA: r ~> (DependencyA.self, arguments: (arg1, arg2)))
```

It really cleans up the registration code. Maybe we should also add the option to pass name to resolve.

For the name for the register function, I haven't come up with anything reasonable, but I will be glad if you give it a try.

There is additional issue I didn't mention:

If you have initializer with an optional parameter, or there are more dependencies than we have generated register function following function is used by compiler:

```
func register<Service, A>(initializer initializer: (A) -> Service, service: Service.Type, name: String? = nil) -> ServiceEntry<Service> 
```

And in A is passed a tuple containing all dependencies e.g. `(DependencyA, DependencyB?, DependencyC)`.  Swinject then tries to resolve the whole tuple and fails. This can be confusing for the users. It would be nice to have some assert to test whether a tuple is passed and display a warning message for the programmer.
Problem is - as far as I know - the tuple doesn't have a type I could test against. I would have to test all possible cases e.g.:

```
if a is (A?, B) || a is (A, B?) || a is (A, B, C?) ... {
assertionFailure()
}
```

Which is again not possible for more than few dependencies. If you have an idea for solution, I would be glad to hear it.

Then there is the question of for how many dependencies and arguments should be the file generated in default. The only issue is the compile time and file size of the extension file. By default I put it to 9 dependencies and 3 arguments.

Cheers
Tomas

**Comment by jakubvano** [comment]
I'm glad to see discussion on this topic :) will give it more thought over the weekend, just one idea after reading the posts above:

I would probably go with prefix operator when automatically inferring dependency types - IMO it better visualizes performed operation:
```
MasterViewModeling(api: <~ r, geocoder: <~ r, locationManager: <~ r, detailModelFactory: <~ r)
```

**Comment by jakubvano** [comment]
As for the issue of replacing multiple arguments with a tuple, I think it might be resolved with Swift 3 (haven't checked it though) given [Proposal 0029](https://github.com/apple/swift-evolution/blob/master/proposals/0029-remove-implicit-tuple-splat.md).

**Comment by jakubvano** [comment]
I can see 3 points in suggested extension:

1. omitting explicit type parameter in the family of `resolve` functions
2. operators
3. auto-registration

#### Ad 1)
IMO if `resolve<T>() ->T?` was added to the main repo than it only makes sense for other functions in resolve family come to with it (`resolve(name:arguments:)` ...). This would however create alternative API for Swinject usage. 
I dont't think it is a good idea to support multiple APIs as it causes inconsistencies and makes it more difficult to adopt by new users. So I conclude that either current API should be deprecated or new one not added at all.

#### Ad 2), 3)
While these two ideas are independent on each other, they both serve the same purpose - creating more concise and declarative syntax. I imagine (@tkohout correct me if im wrong :smile: ) that having both available, you would use operators only when for some issue autoregistration won't work. 
For this reasons (and high learning curve, as @yoichitgy mentioned) I would treat them as a single extension and in line with other non core features (Swinject-CodeGen, SwinjectStoryboard, PropertyLoader) implement them in separate repo.

**Comment by jakubvano** [comment]
As for more complex operators: it make sense to add them when you have operator for simple `resolve`. I'm skeptical towards usage of complex operators, as clarity usually decreases, but I can see the argument for consistency with simple `~>`, and I don't see any harm in adding them.

**Comment by yoichitgy** [comment]
The operator @jakubvano suggested is better than mine.

```swift
MasterViewModeling(api: <~ r, geocoder: <~ r, locationManager: <~ r, detailModelFactory: <~ r)
```

**Comment by yoichitgy** [comment]
I agree with @jakubvano's opinion that `resolve<T>() ->T?` adds alternative API for Swinject usage. I think the first priority and advantage of Swinject is simplicity of usage for new users. It looks good to add the function to a separated repo. This means the `<~` operator must be in the same separated repo. Adding `MyService(dependencyA: r ~> DependencyA.self)` operator to the repo is good too.

So, I would like to add all the features planned in this issue to a separated repo. @tkohout is it ok?

What name looks good for the new repo? I hit on **FunctionalSwinject**, but you guys might have a better name.

**Comment by tkohout** [comment]
Hi,
@jakubvano - thanks for the link, but I tried it in new Swift 3 and it does the same thing. If you check the [proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0029-remove-implicit-tuple-splat.md#proposed-solution) they are saying the passing generic arguments won't be affected.

I was playing with measuring the size of the types, so we could e.g. display warning if the size is too big and it must be tuple:

``` 
MemoryLayout<NSURL>.size //8
MemoryLayout<A>.size //8
MemoryLayout<A?>.size //8
MemoryLayout<AProtocol>.size //40
MemoryLayout<AProtocol?>.size //41
MemoryLayout<AStruct>.size //273
MemoryLayout<AStruct?>.size //274
MemoryLayout<AEnum>.size //1
MemoryLayout<AEnum?>.size //1
MemoryLayout<AEnumString>.size //1
MemoryLayout<AEnumString?>.size //1
MemoryLayout<(A, AProtocol)>.size / 48
```

but struct type size change with number of parameters, and it seems kind of hacky anyway and could break with next swift release. So far, I don't think the issue has solution but I will keep looking.  We could at least put special message to `checkResolved` function for initializer with one parameter, something in style: "make sure there are not optional parameters in your initializer".


Now, as the matter of the extension, I am fine with putting all the operators in separated repo. FunctionalSwinject is fine by me, but it might be better to highlight the Autoregistration feature in the name.

I like the `r~>` but reversing it to `<~r` doesn't make much sense with other functions because it would have to be and is I think bit counter intuitive:

```
MyService(dependencyA: DependencyA.self <~ r, dependencyB: (DependencyA.self, argument: arg) <~ r)
```

Also, as a user of ReactiveCocoa I would be afraid to not to be confused with `<~` operator that binds signal to a property.

At last for Ad 2), 3) @jakubvano, the idea is to use autoregistration as much as possible and let the operators handle more complex cases. For me that's either case with named service:

```
register(MyService.self){ r in
  MyService(r ~> (SomeDependency.self, name: "name") )
}
```

or more deeply nested dependencies that i want to pass dynamic arguments. e.g:
```
register(MyService.self){ r, arg in
  MyService(r ~> (SomeDependency.self, argument: r ~> (AnotherDependency.self, argument: arg) ) )
}
```

Cheers
Tomas

**Comment by yoichitgy** [comment]
(i will comment shortly)

**Comment by yoichitgy** [comment]
Hi @tkohout. First, do you think SwinjectAutoRegistration sounds good for the repository? If ok, I'll create the repository and invite you there.

The tuple problem is difficult. I experienced a similar thing in issue #63, and @jakubvano fixed the issue. We need to investigate the tuple problem for auto registration to find a good solution.

`<~` operator is proposed only for the case without explicit type like this:

```swift
MasterViewModeling(api: <~ r, geocoder: <~ r, locationManager: <~ r, detailModelFactory: <~ r)
```

If it takes explicit type or parameters, `r~>` looks preferable as you said.

```swift
register(MyService.self){ r in
  MyService(r ~> (SomeDependency.self, name: "name") )
}
```

**Comment by yoichitgy** [comment]
@jakubvano, are you also interested in being a member of Swinject org? Your ideas, comments, advices and pull requests, if possible, are always welcome and helpful.

**Comment by jakubvano** [comment]
@tkohout Another heuristic for checking whether an argument is a tuple, might be simply looking for `(` / `)` in type name - braces are not valid symbols in type names, so only false positive might be type with tuple as generic parameter, i.e `Array<(Int, Int)>`, which could be eliminated by only checking non-generic part of name.

As for the name of extension, I would prefer `DeclarativeSwinject` over `FunctionalSwinject`, but `SwinjectAutoregistration` sounds  the most descriptive.

I agree, prefix operator does not make sense for more complex versions. But as I already mentioned, to me
```
MyObject(dependency: r ~> (SomeDependency.self, name: "name")
```
doesn't seem much more (maybe even less) readable than
```
MyObject(dependency: r.resolve(SomeDependency.self, name: "name")
```
so maybe more complex operators are not needed? But if we will have them we should go with operator that makes sense for both, or prefer complex ones, because you only want to use operators in complex cases where aoutoregistration wont work.

I dont think we need to worry about colisions with other frameworks much (besides RAC json mappers come to mind), because context of DI is quite different.

@yoichitgy sure, being a member might motivate me to put some more work to this awesome project 😄

**Comment by tkohout** [comment]
SwinjectAutoregistration sounds good. 

Add the operators: I'm not fan of using two different operators, it might look better, but it's not really intuitive. But I leave the choice to you.

Also remember that you can't put space in between the unary operator and its argument, so it will look more like this:

```
MasterViewModeling(api: <~r, geocoder: <~r, locationManager: <~r, detailModelFactory: <~r)
```

**Comment by jakubvano** [comment]
@type name checking: another type with braces in the name are functions, but again they can be identified by looking for ->.

**Comment by yoichitgy** [comment]
@jakubvano, thank you for making the repository😃

**Comment by jakubvano** [comment]
@yoichitgy my pleasure ;)
@tkohout I've added you to the Autoregistration team, feel free to port your existing code in new repo :) All further discussion on the topic should probably happen there as well

**Comment by jakubvano** [comment]
I tried to sum up discussed / open points to separate issues in the new repo, please check / add if i missed something.

**Comment by yoichitgy** [comment]
Thanks @jakubvano again for submitting the issues to the repo!

FYI: You can change your Swinject membership visibility [here](https://github.com/orgs/Swinject/people) only by yourself. Currently your membership is visible to only the organization members.

**Comment by yoichitgy** [comment]
Closing this issue because it was ported to SwinjectAutoregistration repo. 

https://github.com/Swinject/SwinjectAutoregistration/issues/1
https://github.com/Swinject/SwinjectAutoregistration/issues/2
https://github.com/Swinject/SwinjectAutoregistration/issues/3
