### ISSUE TITLE
From Swinject, is it possible to have an Struct as Singleton (inObjectScope(.Container))?

### ISSUE THREAD

**Issue by eMdOS** [Swinject/Swinject#137]
Currently, I have all the services defined as `Structs`.

There is only one service I would like to have as a singleton (`inObjectScope(.Container)`). Since this service is an `Struct`, the scope `.Container` is not working. It only works if I define this service as `Class`. (Of course, I know the differences between `Structs` and `Classes`, and I know why this is not working).

I think, Swinject could be improved adding this capability. I think, internally, once an `struct` is registered with the `.Container` scope and it needs to be returned, it could be coping all the data to returned `Struct` in order to keep the same data available and simulate the `Singleton` behaviour.

**Comment by yoichitgy** [comment]
I added a unit test (c598e7a844f9ac813116108615a7971e08e77985). Hopefully it would be an answer to this question.

If .Container or .Hierarchy is specified, a factory closure is called only once to simulate `Singleton`, which has only an instantiation.

**Comment by yoichitgy** [comment]
I'm closing this issue because I think my comment above answers to your question. Please feel free to reopen this issue if my answer didn't catch your question correctly.
