### ISSUE TITLE
[Enchantment] How about mark injected dependencies by adding some keyword? 

### ISSUE THREAD

**Issue by CurlyHeir** [Swinject/Swinject#140]
In framework for java (  Dagger ) you have possibility to add Annotation `@Inject` to actually inject components from containers, Swinject works little bit different, but seeing injected dependencies marked by `@Inject` annotation helps to understand code for me. 

How about adding to Swinject special keyword like `@Injected`? 
it would looks like 
```
@Injected
var httpClient : HTTPClient

```

What do you think?

**Comment by yoichitgy** [comment]
It's nice to have the feature when Swift supports custom annotations.

**Comment by CurlyHeir** [comment]
sorry, my bad, i thought they released annotations :D

**Comment by yoichitgy** [comment]
No problems. I really want Swift to support custom annotations😃 Maybe in Swift 4 or 5.
