### ISSUE TITLE
Injection with arguments returns nil

### ISSUE THREAD

**Issue by CurlyHeir** [Swinject/Swinject#141]
Hey, 
sorry for issue spam but i cannot run swinject in my project for 2 days

i have flow controllers in project, that mean that i have additional layer between UIViewController and UINavigationController. But i cannot use it, i'm getting error when i try to pass argument.

I created FlowControllersAssembly of AssemblyType, something like that: 
```
class FlowControllerAssembly: AssemblyType {
    
    func assemble(container: Container) {
        
        container.register(FlowControllerCoordinatorService.self) { r in
            return FlowControllerCoordinator()
        }.inObjectScope(.Container)
        
        container.register(MagazinesFlowController.self) { r, storyboard, navigationController in
            MagazinesFlowController(storyboard: storyboard, navigationController: navigationController)
            }.initCompleted { (r, flowController) in
                flowController.userModel = r.resolve(UserModelService.self)
        }
        
// problem here
        container.register(DashboardFlowControllerService.self) { r, storyboard  in
            return DashboardFlowController(storyboard: storyboard)
        }
    }
}
```
and my AppDelegate 

```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
    let container = Container()
    
    var assembler : Assembler?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    self.assembler = try! Assembler(assemblies: [
            ClientAssembly(),
            ViewControllerAssembly(),
            ModelAssembly(),
            FlowControllerAssembly()
        ], propertyLoaders: nil, container: self.container)

     let bundle = NSBundle(forClass: DashboardViewController.self)
        let storyboard = SwinjectStoryboard.create(name: "Main", bundle: bundle, container: self.container)
        SwinjectStoryboard.defaultContainer = self.container
    let coordinator = container.resolve(FlowControllerCoordinatorService.self)
// flow will be nil :( 
    let flow = self.container.resolve(DashboardFlowControllerService.self, argument: storyboard)
    coordinator!.continueWithFlowController(flowController: flow!)
return true
}
```

if i remove argument from register 
```
container.register(DashboardFlowControllerService.self) { r  in
            return DashboardFlowController(storyboard: UIStoryboard())
        }
```
and try to resolve this flow controller: 
```
let flow = self.container.resolve(DashboardFlowControllerService.self)
```
flow will be returned propertly 

I'm doing something wrong? 
any help appreciated

**Comment by CurlyHeir** [comment]
I investigated it futher, seems that Swinject cannot take as argument anything, i mean if i wrap UINavigationController or UIStoryboard, i can pass this without any problem, otherwise resolve dependency with arguments like Storyboard or NavigationController will return nil :/
My wrapper: 
```
final class ArgumentBox<T :AnyObject> {
    weak var argument: T?
    
    required init(argument: T) {
        self.argument = argument
    }
}
```

**Comment by jakubvano** [comment]
From the quick pass over your code it seems that type of `storyboard` parameter in your constructors is `UIStoryboard`, i.e. `DasbhoardFlowController.init(storyboard: UIStoryboard)`.

If that is the case,  
```
container.register(DashboardFlowControllerService.self) { r, storyboard  in
   return DashboardFlowController(storyboard: storyboard)
 }
```
sets the type of `storyboard` argument to `UIStoryboard`, while when you call the resolve method, you are invoking it with argument of type `SwinjectStoryboard` - swinject can't tell that they are in fact related, so it fails, because it couldn't find registration with exactly specified arguments.

Easy way to solve this would be to explicitly upcast:
```
 let flow = self.container.resolve(DashboardFlowControllerService.self, argument: storyboard as UIStoryboard)
```

**Comment by yoichitgy** [comment]
@jakubvano, thank you for the answer.
@CurlyHeir, [this document](https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#registration-keys) might be helpful to understand the background of the issue:

**Comment by CurlyHeir** [comment]
SwinjectStoryboard inherits from UIStoryboard, so why polymorphism don't work in this case? 
so, if i want pass argument that conforms to some protocol, it's not possible? 
i mean 
```
container.register(DashboardFlowControllerService.self) { r, storyboard, context  in
   return DashboardFlowController(storyboard: storyboard, context: context)
 }
```
and 
```
return DashboardFlowController(storyboard: SwinjectStoryboard, context: Context)
```
when Context is some protocol, then it's not possible to resolve dependency from Swinject, cause type of passed argument is diffrent from parameter type, thats right?

**Comment by yoichitgy** [comment]
I suggest reading [this document](https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#registration-keys) and trying your code. I think it's the best way to understand what Swinject can do and cannot.

**Comment by yoichitgy** [comment]
Closing this issue. @CurlyHeir, please feel free to reopen this issue if you still see the issue after the try👍
