### ISSUE TITLE
Enable "Require Only App-Extension-Safe API" to remove warning linking against dylib in application extensions

### ISSUE THREAD

**Issue by admeister** [Swinject/Swinject#15]
Can the "Require Only App-Extension-Safe API" flag be enabled to stop the warning "linking against dylib not safe for use in application extensions" when referencing Swinject in an extension.

**Comment by yoichitgy** [comment]
I checked v0.3 and I think the flog is set to YES. My misunderstanding??

**Comment by yoichitgy** [comment]
Reference document:
https://developer.apple.com/library/watchos/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by admeister** [comment]
My bad, I was still on 0.2.3.

Great framework btw ;)

**Comment by yoichitgy** [comment]
Ok, thanks.

I started using [jspahrsummers/xcconfigs](https://github.com/jspahrsummers/xcconfigs), and the flag was set to YES unconsciously and greatly.
