### ISSUE TITLE
Swinject no longer compiles with Xcode 8 release version

### ISSUE THREAD

**Issue by jlyonsmith** [Swinject/Swinject#150]
I installed Xcode 8 from the app store today and upgraded my Swinject based app to Swift 3.0.  I see complaints from Xcode saying that the Swinject and SwinjectStoryboard projects need to be upgraded to Swift 3.0 syntax.  There are numerous issues mostly relating to the need to put `_` as the explicit external name of the first parameter and need to use `open` instead of `public` for classes visible outside the module.

This is obviously a blocking issue for projects wishing to upgrade to Swift 3.0 using the final release.

**Comment by jlyonsmith** [comment]
In order for me to get past this it was necessary to convert the Swinject and SwinjectStoryboard projects and deselect all the proposed changes then click OK.  Is this a problem with the project file generated by Cocoapods perhaps?  Also, had some things than needed to be updated in my source such as lowercase enum's (obvious) and adding `ResolverType` to resolver closures (not so obvious)

**Comment by yoichitgy** [comment]
Which versions of Swinject and CocoaPods (or Carthage) did you use?

I checked Swinject v2.0.0-beta.2 with Xcode 8 GM. As far as I know, most of types and method can be `public` rather than `open` in Swinject because not so many things are overridable.

**Comment by jlyonsmith** [comment]
I've also found it was necessary to upgrade to Cocopods 1.1.0.rc.2 in order to make the Swift conversion messages go away for good for all my pure Swift pods.

**Comment by lha-ryq** [comment]
Yes. Upgrading to Cocopods 1.1.0.rc.2 fixed the issue for me. Now **Use Legacy Swift Language Version** for both Swinject/SwinjectStoryboard is set to **No** by default.

**Comment by jlyonsmith** [comment]
@yoichitgy It looks like you could close this issue if you add the recommendation to use Cocoapods 1.1.0.rc.2 and above.
