### ISSUE TITLE
Add a way to log failing resolution

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject#154]
Idea from: https://github.com/Swinject/Swinject/issues/153#issuecomment-248351479

> as user-friendliness usually beats documentation, maybe we could implement some run-time warning messages similar to [checkedResolved](https://github.com/Swinject/SwinjectAutoregistration/blob/master/Sources/AutoRegistration.swift#L682), which would somehow log that resolve failed, what arguments were given, and maybe some suggestion to what might be the problem

```
Resolving of MDFDataSource failed.
Name: -
Arguments: UITableView!, MDFFetchedResultsController

Found similar registration for MDFDataSource:
Name: -
Arguments: UITableView, MDFFetchedResultsController
```

**Comment by jakubvano** [comment]
Implemented by #160
