### ISSUE TITLE
Xcode still asks for Swift conversion of Swinject

### ISSUE THREAD

**Issue by sialcasa** [Swinject/Swinject#162]
I've created a new project from scratch, did a pod init and changed the podfile to:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
use_frameworks!

target "mobiped" do
  pod 'Swinject', '2.0.0-beta.2'
end
```

Then I did a pod install and opened the workspace in XCode. 

Now the problem: XCode still askes me to convert swinject to Swift 2.3 / 3, otherwise I get compile errors.

What did I wrong?

**Comment by yoichitgy** [comment]
Please make sure you use CocoaPods 1.1.0.rc.2 or later.

**Comment by yoichitgy** [comment]
@sialcasa, resolved the issue?

**Comment by sialcasa** [comment]
Yes thank you
