### ISSUE TITLE
Problems with registerForStoryboard vs storyboardInitCompleted

### ISSUE THREAD

**Issue by vladiulianbogdan** [Swinject/Swinject#173]
Hi!

The documentation tells us to use the 'storyboardInitCompleted' method. When I used it I was receiving an error because 'storyboardInitCompleted' method didn't exist in Container.

I saw the commit that modified the name of the method from 'registerForStoryboard' to 'storyboardInitCompleted' but my version of framework (included via Podfile) doesn't contain this modification.

This is my Podfile. Basically it is using the same version as the ones specified in the documentation.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0' # or platform :osx, '10.10' if your target is OS X.
use_frameworks!


target :InjectionExample do
    pod 'Swinject', '2.0.0-beta.2'
    pod 'SwinjectStoryboard', '1.0.0-beta.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

I have changed to 'registerForStoryboard' and everything is working fine but I think there is a problem in the documentation. Anyhow, good job, guys!

**Comment by yoichitgy** [comment]
The documentation is updated before releasing the latest API. Thanks for finding the currently released API by yourself!
