### ISSUE TITLE
[Question] How to make Lazy providers

### ISSUE THREAD

**Issue by PabloLerma** [Swinject/Swinject#176]
Hi!

I'm migrating our app (mix Objc/Swift) from Typhoon to Swinject. 
The migration is _almost_ over but I'm having circular dependencies issues that I'm fixing with the `initCompleted` method according to the documentation.

We have a lot of providers that grant us to have lazy instantiation and I would like to ask if there is a better method with Swift+Swinject (i.e. with closures?).

In case it helps, this is an current example:

```
// Provider is in Objective-c since our app is currently being ported 
// and we have a lot of Objective-c around
@protocol PLSettingsViewControllerProvider <NSObject>

@property (nonatomic, strong, readonly) id<SettingsControllerProvider> settingsControllerProvider;
- (PLSettingsViewController *)viewControllerWithUser:(PLUser *)user;

@end
```

```
container.register(PLSettingsViewControllerProvider.self) { r in
			let settingsViewControllerProviderImp = SettingsViewControllerProviderImp()
			settingsViewControllerProviderImp.settingsControllerProvider = r.resolve(SettingsControllerProvider.self)
			return settingsViewControllerProviderImp
		}
```

```
final class SettingsViewControllerProviderImp : NSObject, PLSettingsViewControllerProvider {

		var settingsControllerProvider: SettingsControllerProvider!

		func viewControllerWithUser(user: PLUser) -> PLSettingsViewController {
			return PLSettingsViewController(user:user, settingsControllerProvider:self.settingsControllerProvider)
		}
	}
```

I'd fix this with _initCompleted_ and removing the `readonly` from the `settingsControllerProvider` property protocol but I don't know if there is a better method, what do you think?

Thanks!

**Comment by jakubvano** [comment]
Hi @PabloLerma!

`Swinject` doesn't have the concept of lazy instantiaton - instead it provides `initCompleted` method as you already figured out :) I would make one change to your proposed solution though:
I wouldn't remove `readonly` from protocol definition because interfaces should not be dependant on DI layer - instead, this is common pattern with circular dependencies (as documented [here](https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#initializerproperty-dependencies))

```
container.register(PLSettingsViewControllerProvider.self) { _ in  SettingsViewControllerProviderImp() }
    .initCompleted { r, p
        let provider = p as! SettingsViewControllerProviderImp
        provider.settingsControllerProvider = r.resolve(SettingsControllerProvider.self)
    }
```

**Comment by PabloLerma** [comment]
Hi @jakubvano ,

Thanks for answering!, I didn't think about the force casting although it was in the documentation :(

Finally I've finally thought in another solution, instead of use an object having the dependencies even before the creation function is called I changed it to be a function returning a function like this:

`typealias SettingsViewControllerProvider = (user: PLUser) -> SettingsViewController`

	func createSettingsViewController(r: ResolverType) -> SettingsViewControllerProvider {
		return { user in
			let settingsControllerProvider = r.resolve(SettingsControllerProvider.self)
			return SettingsViewController(user:user, 
                      settingsControllerProvider:settingsControllerProvider)
		}
	}

Then the object which needs this dependency just have to call in the assembly:
 `object.settingsViewControllerProvider = self.createSettingsViewController(r)`

and in the object implementation:
`let settingsVC = object.settingsViewControllerProvider(user: self.user)`

This way the dependencies are just created with the class needs this specific dependency and not in the parent object creation.

**Comment by jakubvano** [comment]
It is definitely a way :) I used to toy with similar idea in one of my projects and decided against approach like this:

`SettingsViewControllerProvider` can be thought of as a [factory](https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)) for `SettingsViewController` - doesn't matter if it is protocol or function typealias, concept is the same. In this approach you are basically implementing this factory via thing (function, object w/e) that depends on `ResolverType`.

In this case implementation is quite simple, but it establishes a pattern, and there might be cases where factory implementations might be more complicated - and having logic dependant on DI framework is IMO not a good idea..

So I would probably keep `protocol` version, possibly remove `settingsControllerProvider` from interface (AFAICS it is not needed in protocol, only in implementation), and made it a constructor dependency of `SettingsViewControllerProviderImp `

Just my 2¢ ;)

**Comment by PabloLerma** [comment]
Thanks @jakubvano I'd end to migrate all dependencies and then check which approach is better for our codebase.
I'd close this issue. Thanks again!
