### ISSUE TITLE
Any timetable for 2.0.0 coming out of beta?

### ISSUE THREAD

**Issue by irace** [Swinject/Swinject#183]
Thanks in advance!

**Comment by yoichitgy** [comment]
Thank you for asking this important question. We plan completing #165 , #139 and some other issues before getting out of beta. We have no exact time schedule. API might not be stable, but quality is stable as far as we checked.

**Comment by irace** [comment]
@yoichitgy Thanks for the update!

**Comment by Jan0707** [comment]
Just a beginner's question while we're waiting: How can I force the swift package manager to install the 2.0 beta ?

**Comment by yoichitgy** [comment]
We'll release v2.0.0 after Pull Request #215 is merged.

**Comment by yoichitgy** [comment]
Finally we released v2.0.0. Thanks everyone😃
