### ISSUE TITLE
Enhancement of API for weak singletons

### ISSUE THREAD

**Issue by thalmicMark** [Swinject/Swinject#185]
I'd like to make a feature request for weak singletons. There are many cases in your app where you need to use a singleton, but the issue is the singleton will live on for the lifetime of the app.

Instead, I propose weak singletons. Essentially Swinject would maintain a weak reference to the class when it is resolved instead of a strong one. Anyone else who resolves the class while the first resolved instance exists will thus get that same instance. When all resolved instances are released, the singleton can then be de-initialized, since Swinject itself is not holding onto it. If someone else then resolves the class again, a new instance will be created.

Thoughts?

**Comment by yoichitgy** [comment]
I've also wanted to add weak singleton feature. After #165, it looks easier to implement it.
