### ISSUE TITLE
Pointers are different when using the `.container` object scope

### ISSUE THREAD

**Issue by bensarz** [Swinject/Swinject#187]
Is this to allow for thread safety?

For example: 
```swift
container.register(SettingsProviding.self) { _ in
    SettingsProvider(isLoggedIn: true)
}.inObjectScope(.container)

var settingsProviding1 = container.resolve(SettingsProviding.self) // 0x00007fff5f884d20
var settingsProviding2 = container.resolve(SettingsProviding.self) // 0x00007fff5f8849a8
```

**Comment by yoichitgy** [comment]
Is SettingsProviding a class or struct? Can you provide a small example code to reproduce the problem?

Thread safety is mentioned here:
https://github.com/Swinject/Swinject/blob/master/Documentation/ThreadSafety.md

**Comment by bensarz** [comment]
@yoichitgy you can check here:
https://github.com/bensarz/swinject-demo

**Comment by yoichitgy** [comment]
Tell me the steps to reproduce the issue in the project?

**Comment by bensarz** [comment]
all you need is to run Carthage:
`$ carthage update --platform iOS`

Then open the project and run it, look at the console to see the pointer differences.

**Comment by yoichitgy** [comment]
I confirmed the pointers taken by `withUnsafePointer` were different, but instances compared by `===` were identical. Also I ran `po settingsProviding!` in Xcode debug console, and confirmed returned instances were identical.

The diff code I used is:

<img width="652" alt="screen shot" src="https://cloud.githubusercontent.com/assets/965994/20141306/140052b4-a6d3-11e6-8f10-c341078d509c.png">

It looks related to `withUnsafePointer` and Swift memory layout. Would you investigate further about them? It is appreciated if you write your investigation result here.

**Comment by yoichitgy** [comment]
It might be good to ask at Stackoverflow as a general question about Swift (without talking about Swinject). I think Swift experts will catch the very interesting question.

**Comment by bensarz** [comment]
Great find!
I should have tested that with `===`, thanks for finding out!

**Comment by yoichitgy** [comment]
Great to hear!. It's nice if you ask about the different pointers by `withUnsafePointer` at Stackoverflow, and paste its link to this issue thread.

**Comment by bensarz** [comment]
Let's see what the community has to say:
http://stackoverflow.com/questions/40509869/why-is-withunsafepointer-using-a-new-pointer-or-different-pointers
