### ISSUE TITLE
Playground Failure: no such module 'Swinject'

### ISSUE THREAD

**Issue by RLovelett** [Swinject/Swinject#20]
When trying to open the playground on d3339282417f9014cbb9346e1684d0c75f2ba6ce I am getting the following error:

>  Playground execution failed: /var/folders/cv/6rpdnxyn7qv8vql_5gbvpjz00000gn/T/./lldb/61022/playground1.swift:2:8: error: no such module 'Swinject'
import Swinject

Using Xcode Version 7.1 (7B91b).

**Comment by RLovelett** [comment]
I'm sorry. [RTFM](https://github.com/Swinject/Swinject#play-in-playground)

**Comment by yoichitgy** [comment]
It's ok. You just need, as you see, to build the project first, then run the playground. Someone else who gets the same error might be able to find this issue.

**Comment by ukushu** [comment]
The same issue.

I have:
1. Open project
2. Build SwinInject-iOS> Mac
3. Open playground

There is absent **Editor > Execute Playground** menu so no ability to choose it. Even on project window, even on playground window.

Error of playground is the same: `no such module 'Swinject'`

What I did wrong?
