### ISSUE TITLE
Injecting ResolverType

### ISSUE THREAD

**Issue by jordancamara** [Swinject/Swinject#200]
Is there any way to inject a ResolverType into an object? I'm needing to inject this into a singleton controller that is responsible for resolving other controllers and navigating to these other controllers.

**Comment by jordancamara** [comment]
Nevermind. I figured it out. I just had to pass the resolver in the factory to the object when I create it. So:

`container.register(Class.self) { r in return Class(resovler: r) }`

**Comment by badeleux** [comment]
That's anti-pattern - [Why?](http://www.devtrends.co.uk/blog/how-not-to-do-dependency-injection-the-static-or-singleton-container)
