### ISSUE TITLE
Does Swinject support objective-c?

### ISSUE THREAD

**Issue by oronbz** [Swinject/Swinject#207]
If i write my container in swift, can it also support objective-c classes?

**Comment by jakubvano** [comment]
Yes, it can - you cannot use Swinject from Obj-c code, but Swift code has full access to Obj-c classes, and Swinject doesn't care whether class was written in Obj-c or Swift.

**Comment by yoichitgy** [comment]
I'm closing this issue because the answer looks clear.

**Comment by buaaluwentao** [comment]
@yoichitgy, sorry, I am new to Swift，can you show me how can I use Swinject in my obj-c project，for example, what is the first param for register of Container.I always failed with compile error [Cannot convert value of type 'Protocol' to expected argument type 'AnyObject.Protocol']
----------------------------------------------------------------------------
this is my code fragment
public class func registerService(anyProtocol: Protocol, anyClass: AnyClass) {
        DIContainer.container.register(anyProtocol.self) { _ in anyClass.init() }
},
any help, thk you
