### ISSUE TITLE
Register types that conforms to protocol with extension

### ISSUE THREAD

**Issue by zefender** [Swinject/Swinject#209]
Hello Jakub!
Can't find the solution on my case:
```swift
protocol SomeHandler: class {
    func foo()
    func do()
}

extension SomeHandler {
     // default empty impl. func foo() is optional when I adopt to protocol
     func foo() {  }
}


protocol MyProtocol: SomeHandler {
    func myFunc()
}


final class MyClass: MyProtocol {
     func do() {
          // impl
     }
}
```
When I try to register MyProtocol in container I get the error "Ambiguous reference to member 'register(_:name:factory:)'". And there is no error if I will remove SomeHandler inheritance from   MyProtocol.

**Comment by yoichitgy** [comment]
Hi @zefender, I tried the following code in a playground, and it worked (printed "myFunc"). I changed `func do()` to `func bar()` because `do` had conflict with a keyword of Swift lang.

```swift
protocol SomeHandler: class {
    func foo()
    func bar()
}

extension SomeHandler {
    // default empty impl. func foo() is optional when I adopt to protocol
    func foo() {  }
}

protocol MyProtocol: SomeHandler {
    func myFunc()
}

final class MyClass: MyProtocol {
    func bar() {
        // impl
    }
    
    func myFunc() {
        print("myFunc")
    }
}

container.register(MyProtocol.self, name: "🏭") { _ in MyClass() }
let mine = container.resolve(MyProtocol.self, name: "🏭")!
mine.myFunc()
```

Can you show a sample registration code to reproduce the error?

**Comment by yoichitgy** [comment]
@zefender please feel free to reopen this issue with more info if you still see the problem😉
