### ISSUE TITLE
How to remove storyboard support?

### ISSUE THREAD

**Issue by sergthedeveloper** [Swinject/Swinject#210]
Hi, 
I'm not going using ViewController injections
Can I somehow turn off storyboard support and these log messages?

```
Swinject: Resolution failed. Expected registration:
	{ Service: UIViewController, Name: "UIViewController:", Factory: (protocol<PropertyRetrievable, Resolvable>, UIViewController) -> UIViewController }
Available registrations:
```

**Comment by basalphenaar** [comment]
`Container.logingFunction = nil` turns off the log(g)ing (Yes, there is a spelling error in there :) )

**Comment by yoichitgy** [comment]
Thanks @basalphenaar for the answer and pointing out the typo.

@sergthedeveloper, if you use Swinject v2, the storyboard support is turned off if you don't install SwinjectStoryboard. If you use Swinject v1, SwinjectStoryboard is included in Swinject framework, but you can only ignore it.

**Comment by sergthedeveloper** [comment]
Thanks, guys!
Will turn off logging
I'm using '1.1.5' for Swift2.3
