### ISSUE TITLE
Multiple service instances created when registering services .inObjectScope( .container )

### ISSUE THREAD

**Issue by josephbeuysmum** [Swinject/Swinject#219]
My understanding of Swinject is a lot weaker than some of you, but my understanding from the documentation at [ https://github.com/Swinject/Swinject/blob/master/Documentation/ObjectScopes.md ] is that .inObjectScope( .container ) should create singletons [with-a-small-s]. Right? Well I've just updated from beta to the _stable_ version 2.0.0 and unfortunately one of my services is being created at least twice (I say "at least" because this is causing a crash immediately after the app launches, so I don't know yet know what happened beyond that). This is happening with code that 1. was working with the beta release; and 2. which has only been altered to change registerForStoryboard to storyboardInitCompleted, and .none to .transient

I can attach sample code, but the project I'm working on is covered by an NDA, so I'd have to spend some time rewriting it so that it doesn't expose sensitive information (...sigh...) I can do that though if it would help, just let me know.

**Comment by yoichitgy** [comment]
The problem might relate to these:

- https://github.com/Swinject/Swinject/pull/164
- https://github.com/Swinject/Swinject/issues/158
- https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark

**Comment by josephbeuysmum** [comment]
Thanks @yoichitgy I'll look into those.

**Comment by yoichitgy** [comment]
No problems👍
