### ISSUE TITLE
Swift 3.0.1 Issues

### ISSUE THREAD

**Issue by igordeoliveirasa** [Swinject/Swinject#220]
I've been facing with a lot of issues using Swinject 2.0.0 and Swift 3.0.1. Like: "Extraneous argument label name in call Container.Arguments.swift" and a lot of other compatibility issues.

What Am I doing wrong?

**Comment by yoichitgy** [comment]
Can you attach a screenshot image of Xcode showing the error?

**Comment by yoichitgy** [comment]
Is this issue related?
http://stackoverflow.com/questions/36421716/error-extraneous-argument-label-no1-in-call

**Comment by yoichitgy** [comment]
@igordeoliveirasa please feel free to reopen this issue with more information if you still face the problem😉
