### ISSUE TITLE
Optionals on registering with arguments

### ISSUE THREAD

**Issue by Mijail** [Swinject/Swinject#225]
Hi There! I am not sure if this was posted before but if it is I am sorry.

I have something like this:

```
container.register(SomeAbstractClass.self) { (r:Resolver, type:String) in
              return r.resolve(SomeConcreteClass, name:type)!
}
```

Then somewhere else I have this:
```
var type:String! = "blah"
let someAbstractClass = container.resolve(SomeAbstractClass.self, argument:type)!
```

And it never resolves it. My guess is that it is because type variable is `String!` instead of `String`. Replacing it with `String` solves it but I need it to be `String!`. It is weird since in all swift you can exchange both of them and it works just fine.

Any help would be appreciated.

Thanks!

**Comment by serges147** [comment]
For me it looks like you misuse factory you are registering. Most of the time you just instantiate a concrete class inside factory closure. Like following:
`container.register(SomeAbstractClass.self) { (r:Resolver, type:String) in
              return SomeConcreteClass()
}`
Unless you really have somewhere else registration for the SomeConcreteClass. Do you?

**Comment by yoichitgy** [comment]
Thanks @serges147 for your prompt answer😃👍👍 @Mijail please check his answer😉

Talking about the type, Swinject does not convert `String!`, which is an optional type, to `String`. A cast like below might be a workaround. 

```swift
var type:String! = "blah"
let someAbstractClass = container.resolve(SomeAbstractClass.self, argument:type as String)!
```

**Comment by Mijail** [comment]
Hi everyone, thanks for you answer.

Yes I know I can do that, and yes I have registered that class somewhere else as I do modular registration, is that a bad practice?

Yeah I know I could do the "!" trick but I just wondered as on all swift you can pass String! as String or any optional with "!" and its respective class without the need of any cast and it still works as expected.

Again, thanks for your answers :)
