### ISSUE TITLE
Resolve without parameters

### ISSUE THREAD

**Issue by ManWithBear** [Swinject/Swinject#229]
Is here reason to require type parameter for no arguments resolve function? 
Right now I use extension for Resolver to bypass it.
```
extension Resolver {
    func resolve<Service>() -> Service? {
        return resolve(Service.self)
    }
}
```

**Comment by skerkewitz** [comment]
Was about to ask the same question.

**Comment by yoichitgy** [comment]
Basically, we can give type inference in the following 3 ways, and I've chosen the 1st one because it sounds natural in English and consistent for `register` and `resolve`.

```swift
container.register(MyType.self) { MyImplementation() }
let a = container.resolve(MyType.self)!
// or
container.register() { MyImplementation() } as MyType
let b = container.resolve() as? MyType
// or
container.register() {
    let t: MyType = MyImplementation()
    return t
}
let c: MyType = container.resolve()!
```

**Comment by ManWithBear** [comment]
In my opinion for registration preferred A and for resolving C (but left A for specific cases)
Pros:
- less code to write
- easy to handle changes in dependencies (change dependency from one type to another)
Cons:
- you should to check class implementation to see what exactly type you trying to resolve (not big deal)

Right now in my project:
```swift
container.register(SideMenuPresenter.self) { r in
   return SideMenuPresenter(interactorInput: r.resolve()!, routerInput: r.resolve()!)
}.initCompleted { (r, presenter) in
   presenter.view = r.resolve()
}
```
Which looks better that:
```swift
container.register(SideMenuPresenter.self) { r in
   let interactor = r.resolve(SideMenuInteractorInput.self)!
   let router = r.resolve(SideMenuRouterInput.self)!
   return SideMenuPresenter(interactorInput: interactor, routerInput: router)
}.initCompleted { (r, presenter) in
   presenter.view = r.resolve(SideMenuViewInput.self)
}
```

**Comment by jakubvano** [comment]
There has already been some discussion about fundamentally changing Swinject API, you can find it in #132.
Basically, the conclusion was we want to keep current approach, mostly for backwards compatibility and clarity reasons. 
We decided to include extensions which reduce the boilerplate in [SwinjectAurtoregistration](https://github.com/Swinject/SwinjectAutoregistration) module - I suggest you check it out. It contains the syntax you sugested, and more cool stuff 😄

**Comment by ManWithBear** [comment]
For now will stay with my extension.
Autoregistration looks awesome! Will check it later.
Thanks.

**Comment by yoichitgy** [comment]
Thanks @ManWithBear for talking about the advanced topic😃 Simply speaking, `presenter.view = r.resolve()` is good only for advanced users.

`presenter.view = r.resolve(SideMenuViewInput.self)` works even if the type of `view` property is a subclass of `SideMenuViewInput` or a protocol.

`presenter.view = r.resolve()` works only if the type of `view` property is `SideMenuViewInput`, and this is confusing for beginners.

**Comment by leonid-s-usov** [comment]
I have peeked this when reviewing `Dip` dependency injection library for swift. Following their example I have created my extension like this

```
    public func resolve<Component: MyComponentType>() throws -> Component {
        if let c = self.container.resolve(Component.self) {
            return c
        } else {
            throw Error.componentNotFound(Component.self)
        }
    }
```

to be used as

    let cImpl = try r.resolve() as ComponentProtocol
