### ISSUE TITLE
Injection between storyboard view controllers

### ISSUE THREAD

**Issue by xdgimf** [Swinject/Swinject#23]
Any tips on how can I do injection between storyboard view controllers.
ie. I have 3 steps (3 UIViewControllers) for creating a user and create the new user object in the first UIViewController. 

UINavigationController
-> UIViewController 1 - create new user object here
  -> UIViewController 2 - inject new user object here
     -> UIViewController 3 - inject new user object here

Thanks,

**Comment by yoichitgy** [comment]
If my understanding of your question is correct, making a user collection class might be good. Every view controller has a property of the collection type, and inject it to the view controllers by [SwinjectStoryboard](https://github.com/Swinject/Swinject/blob/master/Documentation/Storyboard.md).

If you think my answer is not helpful, would you describe more about your case?

**Comment by xdgimf** [comment]
Thanks, is there also a way to make the user collection type object release when the UIViewController 1 is close?

**Comment by yoichitgy** [comment]
For now, Swinject does not support Weak Container Scope (Issue #13), there is no direct way to release the instance of the collection stored in the container.

As a workaround, you can clear the collection to release the user instance when the view controller 1 is closed.

**Comment by xdgimf** [comment]
Thanks a lot
