### ISSUE TITLE
Is it possible to have more detail error logs when there is circular dependency?

### ISSUE THREAD

**Issue by vminc** [Swinject/Swinject#232]
Currently when there is circular dependency, the injection will fail with this error message: "fatal error: Infinite recursive call for circular dependency has been detected. To avoid the infinite call...,". Is it possible to include in the log information that is good to determine what classes cause the circular dependency?

**Comment by yoichitgy** [comment]
Hi @vminc😃 So far, Swinject does not have logging information for possible circular dependency, but I think you don't get the infinite recursive call error if you use property injection:
https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md

**Comment by yoichitgy** [comment]
@vminc, was the issue resolved? If not, please feel free to reopen this isseu😉
