### ISSUE TITLE
Swinject releases don't include binary files anymore

### ISSUE THREAD

**Issue by Mackarous** [Swinject/Swinject#233]
Just wondering if you guys had any plans to include the binary framework files again in the release

**Comment by yoichitgy** [comment]
I think it's good to include the binary framework after problems of prebuilt frameworks are solved.

One is ABI stability. Currently we have to rebuild the attached framework to a release when a new version of Swift/Xcode are released. We don't have resource to handle the job.

The other problem is this about debugging:
https://github.com/Carthage/Carthage#dwarfs-symbol-problem

**Comment by Mackarous** [comment]
@yoichitgy Interesting, I wasn't aware of the debugging issues with Carthage.

Thanks for the update!
