### ISSUE TITLE
Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

### ISSUE THREAD

**Issue by mrkd** [Swinject/Swinject#238]
## Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

Xcode - Version 8.3 (8E162), Swift 3.1
  - Swinject (2.0.0)
  - SwinjectStoryboard (1.0.0):
    - Swinject (= 2.0.0)

/Pods/SwinjectStoryboard/Sources/Storyboard+Swizzling.swift:25:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

**Comment by yoichitgy** [comment]
Thanks @mrkd for keeping your eyes on the Xcode release note😃😃😃

The change affects only SwinjectStoryboard, so I posted the issue there:
https://github.com/Swinject/SwinjectStoryboard/issues/45
