### ISSUE TITLE
Support for Swift 3.1

### ISSUE THREAD

**Issue by Mackarous** [Swinject/Swinject#240]
Hey guys, wondering what your timeline is for Swift 3.1

**Comment by yoichitgy** [comment]
Thanks @Mackarous for submitting the issue that everyone wants to know. Did you already find problems of Swinject with Swift 3.1? I'll try downloading Xcode 8.3 and build Swinject with Swift 3.1 in this week.

I think it's good to release a version fixing #241 in Swift 3.0.x before migrating to Swift 3.1. I have no exact timeline, but I'll support Swift 3.1 soon.

**Comment by basalphenaar** [comment]
After recompiling Swinject 2.0 with Cartage for Swift 3.1 (still necessary because Swift is not ABI stable yet) it works just fine for me :)

**Comment by yoichitgy** [comment]
Thanks @basalphenaar👍 I also confirmed building Swinject 2.0 with Swift 3.1 worked for me.

(Only an exception was a log message, which got slightly different to describe type names. However, it doesn't affect users of Swinject.)

**Comment by yoichitgy** [comment]
Project itself was updated to Xcode 8.3 with Swift 3.1 by #252.
