### ISSUE TITLE
Init methods can be called multiple times even with .container scope

### ISSUE THREAD

**Issue by vminc** [Swinject/Swinject#242]
I'm unclear if this is an issue with just SwinjectAutoregistration or Swinject, so I post this in both SwinjectAutoregistration and here.

With the following registration, I would expect that the init method for A is called once because I marked A as .container (Singleton) scope, but it seems to be called multiple times. Is this the expected behavior or is there something that I'm missing?

```Swift
container.autoregister(
      A.self,
      initializer: A.init)
      .inObjectScope(.container)
container.register(B.self) { r in r.resolve(A.self)! }
container.register(C.self) { r in r.resolve(A.self)! }
```

`A.init` is still called twice even if I mark B and C as container scope

```Swift
container.autoregister(
      A.self,
      initializer: A.init)
      .inObjectScope(.container)
container.register(B.self) { r in r.resolve(A.self)! }      .inObjectScope(.container)
container.register(C.self) { r in r.resolve(A.self)! }      .inObjectScope(.container)
```

And multiple instances of A is actually created.

I'm on ver 2.0.1 for SwinjectAutoregistration and 2.0.0 for Swinject.

**Comment by jakubvano** [comment]
As you noted in #243, this is expected behaviour as described in [docs](https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark). I will close this, and respond in #243.
