### ISSUE TITLE
When can factory method methods be invoked twice even with .container scope?

### ISSUE THREAD

**Issue by vminc** [Swinject/Swinject#243]
This is more like a question. I just found out that the doc in https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark
said that

> When resolving circular dependencies one of the factory methods (one containing resolution of circular dependency) might be invoked twice. Only one of the resulting instances will be used in the final object graph but in some cases this can be problematic 

My question is when exactly can a factory method be invoked twice? Can this problem be avoided with initCompleted or some guidelines (the example that follows the above quote seems to indicate so). This behavior is problematic for my application because some of the Init methods have side effects.

Moreover, is there a plan to get rid of this restriction? I'm not aware that other DI framework has this behavior for Singleton objects.

**Comment by jakubvano** [comment]
> My question is when exactly can a factory method be invoked twice?

We didn't write exact scenario in thew docs, as it would be needlesly specific:
1. There is circular dependency between two (or more) objects
2. At least one of the objects has the circular dependency resolved in the factory closure
3. That object is the starting point of dependency graph
4. This behaviour is independent on the object scopes

For example in the following scenario `Foo.init(bar)` will be invoked twice (and the second instance will be used)
```swift
container.register(Foo.self) { Foo(bar: $0.resolve(Bar.self)!)  }
container.register(Bar.self) { _ in Bar() }
    .initCompleted { $1.foo = $0.resolve(Foo.self) }
container.resolve(Foo.self)
```

> Can this problem be avoided with initCompleted...

As described in docs, workaround for this is to move the resolution of circular dependency to the `initCompleted` - this will require you to refactor constructor dependency of `Foo` to property dependency:
```
container.register(Foo.self) { _ in Foo() }
    .initCompleted { $1.bar = $0.resolve(Bar.self) }
```

> Moreover, is there a plan to get rid of this restriction?

There were attempts to change this behaviour, but they resulted in further complications. Thus we decided that this behaviour is the lesser evil 😄 For more info see #133, #158, #159, #164

**Comment by yoichitgy** [comment]
I closed this issue because it looked resolved. @vminc, please feel free to reopen this issue if you still have questions.
