### ISSUE TITLE
Using weak scope is leaking objects?

### ISSUE THREAD

**Issue by alexisbronchart** [Swinject/Swinject#256]
I have this dummy object

```
protocol DevTestProtocol: class {}
class DevTest: DevTestProtocol {}
```
which is registered like follows (I'm using an assembly)

```
container.register(DevTestProtocol.self) { _ in
    return DevTest()
}
.inObjectScope(.weak)
```

For testing purposes I added a property in my app delegate

`var devTest: DevTestProtocol?`

and in applicationDidFinishLaunchingWithOptions I resolve the object then forget about it

```
self.devTest = DI.resolve(DevTestProtocol.self)!
self.devTest = nil
```

Is the DevTest instance supposed to be gone by now? 
Because it's not. It still shows in the debug memory graph as a leak (see screenshot).
<img width="2032" alt="screen shot 2017-05-23 at 11 31 43" src="https://cloud.githubusercontent.com/assets/1279527/26347970/8047e830-3fab-11e7-9e44-d240f030b53f.png">

I guess this isn't expected behaviour? Am I missing something? 
It looks like a bug to me and it's messing up my whole setup.
What can we do about this?

**Comment by mpdifran** [comment]
Can you post the `DevTest` class as well? Are there any retain cycles that are keeping it alive?

**Comment by alexisbronchart** [comment]
That's what I'm wondering. At least they don't show up in the debug memory graph. 
This actually happens with the actual empty implementation of DevTest I provided at the top of my post.

**Comment by mpdifran** [comment]
Ok, I can look into adding some tests for this (if there aren't already some), and see if I can track down the problem.

**Comment by alexisbronchart** [comment]
Allright thanks, you can checkout this project to reproduce the issue if needed: https://github.com/alexisbronchart/SwinjectWeakLeak

**Comment by alexisbronchart** [comment]
I just found that if DevTest inherits from NSObject then the leak doesn't show up in the debug memory graph.

**Comment by yoichitgy** [comment]
Thanks @alexisbronchart and @mpdifran!

**Comment by igorkotkovets** [comment]
@yoichitgy, also found the issue in my project :(.  Are there any updates? Or workarounds?

**Comment by yoichitgy** [comment]
Thanks @igorkotkovets for the investigation 👍👍👍 I'll check it.

**Comment by jodyscho** [comment]
Any updates on this issue? I'm seeing it as well. I'm not sure it's an Xcode8 profiling issue. I started noticing it in the app, then confirmed it with the profiler.

**Comment by yoichitgy** [comment]
Thanks @jodyscho for the investigation😃 I’m going to close this issue in Swinject project.

Please anyone feel free to reopen this issue, or open an issue in SwinjectStoryboard project if you find the leak issue is reproducible👍
