### ISSUE TITLE
Override registered class for testing?

### ISSUE THREAD

**Issue by danishin** [Swinject/Swinject#26]
Hello, first of all, great work with swinject! This library makes DI a breeze.

I've posted a question on SO [here](http://stackoverflow.com/questions/33629478/swinject-override-registered-class-in-testing) with `swinject` tag but haven't got any answer from you yet. So I'm reaching out to you to see if you could answer it!

Thanks :smile:

**Comment by danishin** [comment]
Retaining a strong reference to `Container` solves the problem!

**Comment by yoichitgy** [comment]
Hello, sorry for the late reply. I didn't check my email yesterday. That's good to hear you already solved the problem.
