### ISSUE TITLE
Need to force cast to implementation type to prevent EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by kerry** [Swinject/Swinject#265]
I have a minimal implementation of VIPER architecture and I am using Swinject to create the whole module and its dependencies. This is working fine with creating services but when it comes to creating modules, it is giving run time error unless I force cast each VIPER component to individual implementation rather than keeping them as protocols. 

Please find my project here:
https://github.com/kerry/SwinjectBug

The master branch is not working and giving EXC_BAD_ACCESS and I have fixed this in SplashScreenFactory.swift by force casting each component. Please find the commit url.
https://github.com/kerry/SwinjectBug/commit/299daddc77fa70d3b2baa1b7c3ef0694e2df21d7

BaseModule is the super module that every module subclasses.

Is there anything wrong in my usage of the library? Let me know

**Comment by yoichitgy** [comment]
Reference:
https://stackoverflow.com/questions/44416772/swinject-giving-exc-bad-access-code-2-within-a-simple-project-working-if-comp

**Comment by yoichitgy** [comment]
It looks this issue is a private support request. I started answering in the Stackoverflow thread. I'm going to close this issue on GitHub😉
