### ISSUE TITLE
Can't run unit tests - "No such module 'Quick'" error.

### ISSUE THREAD

**Issue by serges147** [Swinject/Swinject#267]
Made exactly as in the `CONTRIBUTING.md` described, step by step. What is missing? Thanks!

**Comment by jakubvano** [comment]
There were some changes to how we manage dependencies, and`CONTRIBUTING.md` was not updated - should be remedied by #268.

Basically, instead of 
```
carthage bootstrap --use-submodules --no-build
```
You should run
```
carthage bootstrap
```

Thanks for pointing this out 👍

**Comment by serges147** [comment]
Thanks! It worked.
