### ISSUE TITLE
registerForStoryboard with arguments?

### ISSUE THREAD

**Issue by danishin** [Swinject/Swinject#27]
I'm trying to assign `register`ed class that accepts arguments to one of my `ViewController` inside `registerForStoryboard`.

```
// Inside setup()
c.register(ViewModel.self) { r, foo in ViewModel(foo: foo) }
c.registerForStoryboard(ViewController.self) { r, vc in vc.vm = r.resolve(ViewModel.self, arg1: ???) }

// Instantiate ViewController ???
sb.instantiateViewControllerWithIdentifier("ViewController")
```

How should I go about doing this? Perhaps, I'm missing something here?

**Comment by yoichitgy** [comment]
Hello. Thank you for pointing out the issue.

The current version of `SwinjectStoryboard` does not have a way to pass arguments to an instantiated view controller. I'll try to add the feature as an update later.

For now, one of workarounds is something like this:

```
// Somewhere you can access both from inside setup() and view controller instantiation.
var foo = ""
let getFoo = { foo }

// Inside setup()
c.register(ViewModel.self) { _ in ViewModel(foo: getFoo()) }
c.registerForStoryboard(ViewController.self) { r, vc in vc.vm = r.resolve(ViewModel.self) }

// Instantiate ViewController
foo = "foo"
sb.instantiateViewControllerWithIdentifier("ViewController")
```

, or register `FooGetter` to the container:

```
c.register(FooGetter.self) { _ in FooGetter() }
c.register(ViewModel.self) { r in ViewModel(foo: r.resolve(FooGetter.self)) }
```

**Comment by yoichitgy** [comment]
It would be nice to add a method like `instantiateViewControllerWithIdentifier(_: arguments:)` to `SwinjectStoryboard`.

@danishin, keep this issue open please? I'll take time to think how I can add the feature.

**Comment by danishin** [comment]
Thanks for your response. Yes, that'd be nice to have. I'll keep the issue open!

**Comment by danishin** [comment]
@yoichitgy Hello, has there been any update to this?

**Comment by yoichitgy** [comment]
I finished refactoring (6cb733d548e5931787f0ae2ff6456927810e2ad5) to implement the storyboard feature, but I got other issues to do (#58, #59, #51).
　
Will you be able to try implementing the feature and sending a pull request❓Your help is really appreciated😃

**Comment by yoichitgy** [comment]
@danishin, I was thinking how to implement the argument feature to `SwinjectStoryboard`, but it was too complicated rather than my expectation because `SwinjectStoryboard` has to inject dependencies not to the instantiating view controller but also its child view controller.

I'm not going to implement the feature, but I got a workaround for your case like this.

```swift
// Inside setup()
let c = Container()
c.register(ViewModel.self) { r, foo in ViewModel(foo: foo) }
c.registerForStoryboard(ViewController.self) { r, vc in vc.vm = r.resolve(ViewModel.self, arg1: ???) }
c.register(ViewController.self) { r, sb, a1 in
    let vc = sb.instantiateViewControllerWithIdentifier("ViewController")
    vc.vm = r.resolve(ViewModel.self, arg1: a1)
    return vc
}

// Instantiate ViewController
let resolvedVC = c.resolve(ViewController.self, arguments: (sb, arg1))
```

Or you might be able to add a `SwinjectStoryboard` to the container instead of passing it as an argument in `resolve` method.

I couldn't find a straightforward solution for the arguments, but always welcome if you get a good idea to simply implement the feature.
