### ISSUE TITLE
Property injection

### ISSUE THREAD

**Issue by Mijail** [Swinject/Swinject#273]
Hey there!

I was wondering if there is some way to use property injection with the instance already created.

The examples I see about property injection create the instance in the same place where the properties get injected, so that doesn't work for me.

Is there a way I could pass the instance and then resolve the properties on that instance depending on the type?

Thanks!

**Comment by Mijail** [comment]
Well I managed to do that using arguments but it would be nice to have an "official" method to do property injection with already created instances.
For anyone curious, it is pretty simple with arguments:
`        container.register(TestViewController.self) { (resolver, vc: TestViewController) -> PauListViewController in
            return vc
        }`

**Comment by yoichitgy** [comment]
We have no official way, but your usage looks good to me. Thanks👍
