### ISSUE TITLE
Attach Carthage archive to the release

### ISSUE THREAD

**Issue by dimazen** [Swinject/Swinject#277]
Hello! Can you please attach framework's archive to the release? This speeds up carthage dependencies update/bootstrap a lot :) 
See [Carthage Readme](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) for the instruction.

Thanks in advance!

**Comment by tkohout** [comment]
Hello, thanks for the suggestion. I am not too familiar with the prebuilt frameworks but pull requests are are welcomed!

**Comment by yoichitgy** [comment]
IMO, less projects provide prebuilt frameworks since Carthage introduced cache build with `--cache-builds` option.
https://github.com/Carthage/Carthage#caching-builds

Let me investigate the latest best practice.

**Comment by dimazen** [comment]
@tkohout I can upload the binary, but PR won't make any sense, since binary attached to the Release and doesn't affect the git repo :)

@yoichitgy I haven't knew about it. Thanks a lot! Probably this gonna resolve the question.

**Comment by dimazen** [comment]
@tkohout according to the comment of @yoichitgy I was able to skip re-build of the dependencies by passing --cache-builds options. This resolved my issue, therefore we can (I believe) close it.
