### ISSUE TITLE
Registering multiple (protocol) types for one concrete implementation

### ISSUE THREAD

**Issue by mariob** [Swinject/Swinject#28]
Hi,

Let's say you have two protocols, __Purchasing__ and __Reserving__. Reserving will reserv a seat and Purchasing will actually purchase a reserved seat:
```
protocol Reserving {
    func reserv() -> Reservation
}

protocol Purchasing {
    func purchase(reservation: Reservation) -> Ticket
}
```
For some reason (that's another discussion :) it makes sense to conform to both protocols in one concrete class, maybe share some state and make things less complex, legacy code base or what ever. For example:
```
class TicketService: Reserving, Purchasing {
....
}
```
We also want/need to register TicketService in the global scope (can only have one instance or things will break :).

So to my question... Would it be possible to register multiple protocols for one instance of TicketService, for example:
```
container.register(Purchasing.self, Reserving.self) { r in TicketService() }.inScopeScope(.Global)
```
Are there any language limitations in swift of doing so?

**Comment by mariob** [comment]
Well, one could actually just create the service instance before invoking the __register__ call, for example:
```
let ticketService = TicketService()

container.register(Reserving.self) { _ in ticketService }
container.register(Purchasing.self) { _ in ticketService }
```

Maybe not as elegant as creating the instance inside the closure :)

**Comment by ilyapuchka** [comment]
@mariob you can use `typealias  TicketServiceProtocol = protocol<Purchasing, Reserving> ` and use it as a type for registration.

**Comment by mariob** [comment]
@ilyapuchka nice move! :+1:

**Comment by yoichitgy** [comment]
@ilyapuchka thank you for answering to the question!

**Comment by serges147** [comment]
@ilyapuchka Solution with typealias-ing of multiple protocols doesn't allow you resolve later by a single protocol

**Comment by mpdifran** [comment]
Yeah, I'd like the ability to have a single concrete class conform to two protocols, and be able to resolve via either of the protocols individually. My use case is placing public functionality of a framework in one protocol, and internal functionality in another. 

Anyone have an idea for what the API could look like for this? I could take a crack at implementing it.

**Comment by serges147** [comment]
@mpdifran look at `implements`
