### ISSUE TITLE
 Infinite recursive call with XIB

### ISSUE THREAD

**Issue by szuniverse** [Swinject/Swinject#284]
Hi

Here is my sample code:
https://drive.google.com/file/d/0B7zDGewz3zO1dFlIUlgzUWFVaFU/view?usp=sharing

I get the following error:
fatal error: Infinite recursive call for circular dependency has been detected. To avoid the infinite call, 'initCompleted' handler should be used to inject circular dependency.: file ... LoginWithDI/Pods/Swinject/Sources/Container.swift, line 180
2017-08-10 15:45:31.945842+0200 LoginWithDI[62820:4215299] fatal error: Infinite recursive call for circular dependency has been detected. To avoid the infinite call, 'initCompleted' handler should be used to inject circular dependency.: file

I tried to use the 'initCompleted' but I couldnt resolve my problem.
Could anyone help me?

thanks in advance

**Comment by yoichitgy** [comment]
Please refer to this document. 
https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md

**Comment by szuniverse** [comment]
Great! Thanks!
