### ISSUE TITLE
Question about: "depth cannot be negative."

### ISSUE THREAD

**Issue by josephbeuysmum** [Swinject/Swinject#289]
Hi. I've been running Swinject successfully for months. Two days ago, my app failed with the following error:

`assert(resolutionDepth > 0, "The depth cannot be negative.")`

This has never happened before or since, it's a total one off. Is it anything to worry about?

**Comment by yoichitgy** [comment]
It looks something wrong with `.graph` scope or another custom scope if you created.

**Comment by josephbeuysmum** [comment]
It happened just once, and never since. Is that not odd?

**Comment by yoichitgy** [comment]
It sounds odd. I can check if you show me the call stack when the issue happens again.

**Comment by josephbeuysmum** [comment]
hasn't happened yet. probably just me doing something dumb once. let's close this.

**Comment by skerkewitz** [comment]
I recently run into the same problem and I don't understand how that is possible.

I'm on 2.1.1 currently. No idea how often it happens as the ```assert()``` is only evaluated in debug mode and the code will not immediately crash in production.
