### ISSUE TITLE
Make `.container` the default object scope

### ISSUE THREAD

**Issue by Herriau** [Swinject/Swinject#291]
The fact that the `.graph` scope is assumed by default led me to very confusing results in so far as I did not expect my factories to be called more than once. It took me a while to figure out what was going on, especially because this concept of object scope isn't mentioned anywhere in the README.

It seems to me that `.inObjectScope(.container)` is the behavior that I have come across in most DI frameworks. Should this be the default instead?

**Comment by Herriau** [comment]
* Php-di
* PHP Symfony's container
* InversifyJS

Regardless of the existence of that ObjectScopes page, I feel like if `.graph` is to remain the default, this should be mentioned in big letters on the main README.

**Comment by olejnjak** [comment]
I'd add my bit to this thread. I also feel like `.graph` scope is not what I need in my apps. But also I understand that changing this would semantically big breaking change. 

But my case is a bit different, my ideal default scope would be `.transient`. I use SwinjectAutoregistration and almost every factory I register assumes that every object return is newly created.

My suggestion would be to keep `.graph` as default scope, but allow developers to change it.

**Comment by yoichitgy** [comment]
Thanks @olejnjak for your idea👍

**Comment by jkaan** [comment]
@yoichitgy I could (try to) create a PR to make the default scope part of the container as a configuration option. What do you think?

**Comment by serges147** [comment]
Yup, once I realized that `.graph` is default scope, I had to look at every and each registration place, and explicitly specify either `.container` or `. transient` depending on context.

**Comment by jakubvano** [comment]
Resolved by #304
