### ISSUE TITLE
Swift 4 migration

### ISSUE THREAD

**Issue by Out1and3r** [Swinject/Swinject#295]
Hi,

Do you have any plans to migrate the project to Swift 4?

Thank you

**Comment by yoichitgy** [comment]
Yes, after migration to Xcode 9 with Swift 3.2.

**Comment by evisoup** [comment]
Is there a timeline for the support of Xcode 9 & Swift 3.2 🙏🏻

Currently experiencing `Module compiled with Swift 3.1 cannot be imported in Swift 3.2` when building project in Xcode 9.

**Comment by yoichitgy** [comment]
I think `Module compiled with Swift 3.1 cannot be imported in Swift 3.2` is a Carthage issue, and Carthage 0.25 resolved it.

I still didn't made a release, but you can use the latest commit in `master` for Xcode 9 and Swift 3.2.

**Comment by gaurav38** [comment]
When can we expect a release for 3.2 and 4.0?

**Comment by gaurav38** [comment]
On a related note, are we removing SwinjectStoryboard? I just downloaded the master branch and it's missing from there.

**Comment by serges147** [comment]
We opted out `SwinjectStoryboard` completely from our projects – it just don't work at all on HighSierra.

**Comment by jeppiebarroga** [comment]
What's the update with this?

**Comment by jakubvano** [comment]
Resolved by #316 

@gaurav38 SwinjectStoryboard has been moved to separate [repository](https://github.com/Swinject/SwinjectStoryboard) a while back - however there are some issues with swift 4, which we hopefully manage to resolve.
