### ISSUE TITLE
Using Swinject in a VIPER like architecture

### ISSUE THREAD

**Issue by siddharthan64** [Swinject/Swinject#301]
Is it advisable to use containers over assemblers in a project with VIPER like architecture? Each container is created with registered services, only when user taps the tab bar item. This rules out the use of `Assembler` to create a container with all the child `Assembly`.  By using containers directly, I feel I can create the parent child hierarchy when the user taps the tab bar item and setting the parent container. This can be done with the Assembler initializers too - `init(parentAssembler: Assembler?)`. Are there any advantages on using the assemblers over containers. Whats your view on this?

**Comment by jkaan** [comment]
I'm not an expert on Swinject, but I might be able to shed some light on what you're asking. 

From what you're saying you are comparing containers and assemblers, however I think those can not be compared. A container is used to register dependencies on while an assembler is used to create a container given a list of assemblies.

I would suggest to use one container to register all of your dependencies at first and while your project grows you could move to using an `Assembler` to create the container (or just a sub-set) by using `Assemblies` to group related dependencies together.

This is a very general answer, but I hope it a answers some of the questions that you have. :)

**Comment by yoichitgy** [comment]
Thanks @jkaan for the answer👍

Some other questions/answers might be also helpful for you😉
https://github.com/Swinject/Swinject/issues?q=is%3Aissue+viper+is%3Aclosed

**Comment by jakubvano** [comment]
Closing this, as answers have been given. @siddharthan64 If you have any followup questions, feel free to reopen it 😉
