### ISSUE TITLE
Please deactivate codeCoverageEnabled to prevent appstore rejection

### ISSUE THREAD

**Issue by BennX** [Swinject/Swinject#309]
Please deactivate codeCoverageEnabled inside of the Swinject-iOS.xcscheme else a carthage dependency build will result in an rejection of Apple for the reason:

> Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

current possible workaround:
https://stackoverflow.com/questions/46160518/xcode-9-carthage-itunes-connect-error-invalid-bundle-disallowed-llvm-instr

**Comment by s4cha** [comment]
Issued https://github.com/Swinject/Swinject/pull/311 to solve this issue :)

**Comment by jakubvano** [comment]
It has turned out to be the Carthage issue, and has been fixed in [Carthage 0.26](https://github.com/Carthage/Carthage/releases/tag/0.26.0).
