### ISSUE TITLE
Init object on swinject registration

### ISSUE THREAD

**Issue by LeonidKokhnovich** [Swinject/Swinject#312]
Hi! I have a manager class that needs to be initialized upon app launch. This manager is used in one of the view controllers that is shown sometime later in the app life circle. Is there a nice way to init dependency on swinject registration without actually injecting it anywhere? Here is a sample code:
```
protocol ManagerType {}
class Manager: ManagerType {}

func registerSwinject() {
  defaultContainer.register(ManagerType.self) { resolver in
            Manager()
            }.inObjectScope(.container)

  defaultContainer.storyboardInitCompleted(CustomViewController.self) { resolver, controller in
            controller.manager = resolver.resolve(ManagerType.self)
        }
}
```

With this code, Manager will be created only when CustomViewController needs to be presented, but my goal is to nicely initialize it during swinject registration.

**Comment by mpdifran** [comment]
Inject it into your `AppDelegate`, either on application launch, or in `AppDelegate.init`. If your object is a singleton, you don't even need to store it in a property.

**Comment by LeonidKokhnovich** [comment]
@mpdifran Thank you for the response. I had this idea, but my concern was that AppDelegate won't use the dependency so I was thinking if there is a better way to do that. But if not, then I will just follow your advice.
