### ISSUE TITLE
One project, two targets, need help

### ISSUE THREAD

**Issue by zarochintsev** [Swinject/Swinject#313]
Hi,
How to use Swinject framework to two projects, which added in one target?

**Comment by zarochintsev** [comment]
![screen shot 2018-01-26 at 5 03 06 pm](https://user-images.githubusercontent.com/5650844/35445615-dc3191b4-02ba-11e8-82c7-ffaeef61fff4.png)

**Comment by jakubvano** [comment]
Hello @zarochintsev, your question is too broad - can you clarify what exactly is the issue? Thanks 😉

**Comment by jakubvano** [comment]
Closing this due to the lack of activity. Feel free to reopen the issue, if you have followup questions / more info.
