### ISSUE TITLE
Question about using Storyboard Segues

### ISSUE THREAD

**Issue by pschneider** [Swinject/Swinject#314]
#Hi,

so we're planning to integrate Swinject into our project. As we want to implement the DI Concept the right way we would need a way to dynamically pass objects between view controllers / view models . Think tapping a table view cell and passing the selected model to a detail view controller. 

So we tried that scenario without passing the container (and therefor depend on the implementation) to the table view controller performing the segue. But that seems kinda impossible. Is there any proposed solution to handle this? We currently set the selected model via `prepareFor(segue:sender:)` as probably done in the most implementations using StoryboardSegues.

Any help appreciated
thanks!

**Comment by jakubvano** [comment]
Hello @pschneider,
From my point of view your question is more about the MVVM architecture than DI framework. I would suggest you ask this on stackoverflow - there you probably have better chance of getting solutions from people experienced with MVVM architecture.
Hope you find a satisfying solution 😄

**Comment by J7mbo** [comment]
@pschneider I DI my view controllers, lazily, if I'm going to segue from one to another. No passing in the container in this instance as that's a service locator.

**Comment by jakubvano** [comment]
I will close this for now -  if you have some followup questions, feel free to reopen this 😉
