### ISSUE TITLE
Swift 4.1

### ISSUE THREAD

**Issue by gilroykilroy** [Swinject/Swinject#336]
Xcode 9.3 is now out:

/App/Carthage/Checkouts/Swinject/Sources/InstanceWrapper.swift:83:11: error: using 'ImplicitlyUnwrappedOptional' in this location is deprecated and will be removed in a future release; consider changing this to 'Optional' instead
extension ImplicitlyUnwrappedOptional: InstanceWrapper {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
          Optional
/App/Carthage/Checkouts/Swinject/Sources/InstanceStorage.swift:82:33: error: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
        get { return components.flatMap { $0.instance } .first }
                                ^
/App/Carthage/Checkouts/Swinject/Sources/InstanceStorage.swift:82:33: note: use 'compactMap(_:)' instead
        get { return components.flatMap { $0.instance } .first }
                                ^~~~~~~
                                compactMap
/App/Carthage/Checkouts/Swinject/Sources/InstanceStorage.swift:99:27: error: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
        return components.flatMap { $0.instance(inGraph: graph) } .first
                          ^
/App/Carthage/Checkouts/Swinject/Sources/InstanceStorage.swift:99:27: note: use 'compactMap(_:)' instead
        return components.flatMap { $0.instance(inGraph: graph) } .first
                          ^~~~~~~
                          compactMap

**Comment by gilroykilroy** [comment]
I opened a PR.

**Comment by jakubvano** [comment]
Resolved by #342 , released with 2.4.0
