### ISSUE TITLE
Type forwarding (small idea from my DI for help)

### ISSUE THREAD

**Issue by ivlevAstef** [Swinject/Swinject#339]
In documentation for new feature "Type Forwarding" you wrote:
"""
Type safety
Unfortunatelly, there is no way in Swift (yet) to ensure that original registration conforms to the forwarded types. If you define forwarding to an unrelated type there will be a runtime crash during its resolution:
"""

But, your can use small another syntax for type safety:
```
container.register(Dog.self) { _ in Dog() }
	.implements(Cat.self) { $0 }
```

And xCode write error during compilation.

How it works:
```
func implements<T>( _ type: T.Type, ..., check: (_ s: Service) -> (T)) { ... }
```
pay attention to the function of checking - we refuse type checking, and we check the object type. But closure `check` never call.

Thanks for support Swift4 - I was starting to think the project was dead.
And thanks new feature: Lazy, Provide - I've been thinking to add them to her or not :)

**Comment by jakubvano** [comment]
Thanks for the idea 👍 however, I see two issues with it: 

2. It does not work properly if one implementation conforms to multiple protocols:
```swift
class MyImplementation: Protocol1, Protocol2 {}
container.register(Protocol1.self) { _ in MyImplementation() }
    .implements(Protocol2.self)

// of course this could be solved by
container.register(MyImplmentation.self) { _ in MyImplementation() }
    .implements(Protocol1.self)
    .implements(Protocol2.self)
```

2. (More importantly) It makes API unclear for typical user, i.e. adds "redundant" closure parameter without apparent reason.

In my experience type unsafety is not too big of a deal in this case, as bugs appear immediately in the developement process.
