### ISSUE TITLE
Question: ResetObjectScope

### ISSUE THREAD

**Issue by gkaimakas** [Swinject/Swinject#346]
Can I reset the object scope of a container without it affecting the parent container?

I am using the MVVM pattern and am registering my repositories in a container e.g: nonPurgeable. My view models are registered in a purgeable container that has as a parent the nonPurgeable container. I want to reset the object scope of the view models container whenever the user logs out but in doing so the parent container objectScope is also reset.

Can I avoid that?

**Comment by jakubvano** [comment]
No, you cannot reset only one of the containers. 

The idea is, that `Container` is responsible for registrations - i.e. how to create an object, and `ObjectScope` is responsible for instance persistence. So in your case I would suggest to use [custom object scope](https://github.com/Swinject/Swinject/blob/master/Documentation/ObjectScopes.md#custom-scopes) e.g. 
```swift
extension ObjectScope {
    static let nonPurgable = ObjectScope(storageFactory: PersistentStorage.init)
}
```
Then register instances from the parent container with `.inObjectScope(.nonPurgable)` (or get rid of multiple containers altogether, if this was their only purpose). 
When you run `container.resetObjectScope(.container)`, non-purgable instances will not be affected.

**Comment by gkaimakas** [comment]
@jakubvano That's so helpful! Thanks!

P.S: `PersistentStorage` was renamed to `PermanentStorage`

**Comment by jakubvano** [comment]
Glad to be helpful 😉 

Thanks for pointing out the old type name 👍 remedied by #347
