### ISSUE TITLE
Effective setup when using separate swift modules

### ISSUE THREAD

**Issue by sprynmr** [Swinject/Swinject#354]
Hey there. So we are modularizing an app, and using Swinject to expose the functionality each module supplies for use in the main app, and other modules.

For this we are exposing an `Assembly` on each module, that the main app then assembles all together. This works great for the resolution of module functionality in the main app, but I'm not sure on the best approach for resolving functionality from sibling modules, or inter-module (registering and using in the same module) since the assembly doesn't expose the container as a property.

That is to say there is no way to access the assember/container from the child module to resolve functionality, even if we hold onto the module `Assembly`.

I saw something about injecting injectors, but that didn't seem to quite solve this issue.

Obviously I could just smash the container into the module one way or another, but I wasn't sure if there was a recommended pattern here.

**Comment by jakubvano** [comment]
I don't think there is such a thing as best practices yet, especially in more complex project setups. 

In my projects we generally have one module where we put generic support stuff (e.g. basic architectural components) - almost all other modules depend on this `Generic` module.
In this module we also expose an `Assembler` to which main `App`module applies all the assemblies from other modules. There is some more infrastructure around this, but in essence that is what we use.

**Comment by sprynmr** [comment]
Ahh, exposing the assembler on an included module is a reasonable solution. Cool. Good to know. Thanks!
