### ISSUE TITLE
Swinject fatalError() crash on resolve 

### ISSUE THREAD

**Issue by ohnu** [Swinject/Swinject#361]
Random crash at /Swinject/Sources/Container.swift, line 298

Xcode version: 9.4.1
Swinject version 2.4.1
SwinjectStoryboard version 2.0.1

Seems that the currentObjectGraph is nil while the resolution depth is not 0.
Unfortunately we do not have any specific step on how to reproduce this as it crashes randomly.

Note: As far as I know we use resolve exclusively on main thread and am not aware of any calls from multiple threads.

![swinject_container_state](https://user-images.githubusercontent.com/1701334/42273378-aac470ac-7f91-11e8-92ea-1183b0546ef5.png)

**Comment by sanojbluejeans** [comment]
I am facing the same issue, did you get any resolution?

**Comment by IgorFedorchuk** [comment]
I have the same crash

**Comment by ohnu** [comment]
On further, investigation we did discover some .resolve(service) code being called on another thread other than the main one.

Moving that to main thread solved the crash.
