### ISSUE TITLE
Optional types on Xcode 10 (Swift 4.2)

### ISSUE THREAD

**Issue by Axadiw** [Swinject/Swinject#368]
Hey, I've got a piece of code that was working perfectly fine in XCode 9 (Swift 4.0), but on XCode 10 (Swift 4.2) it resolves to `nil` only.

I'm registering my own type in the assembly with:

```
container.register(Optional<MyType>.self) {
            (_, myParam: string) in
...

return instance
        }
```

and resolving it like

```
let myInstance = resolver.resolve(Optional< MyType >.self,
                        arguments: "abc")
```

As I've mentioned above, on Xcode this code resolves correctly (to instance of `MyType`) but on Xcode 10 i'm receiving just `nil`. 

Intresting fact is that after placing a breakpoint inside the register clojure, debugger doesn't stop there

**Comment by taher-mosbah** [comment]
@Axadiw see #367 , I think we are having the same issue, please let us know if you identified the cause of this bug.

**Comment by Axadiw** [comment]
Because I don't have `Swinject: Resolution failed. Expected registration` error on the console - I thought that this might be similar, but different issue.

Anyways - until it would be fixed I've used quick workaround - I've just wrapped my object with a struct like

```
struct MyTypeBox {
let myType: MyType?
}
```

and I'm registering `MyTypeBox` in swinject, without an optional

**Comment by romainbiard** [comment]
same issue on my side.
I can't really use this workaround since I'm using an injected  `weak var`(to avoid retain cycle) and thus need to be optional :-/
