### ISSUE TITLE
Lazy injection conflicts with get-only property

### ISSUE THREAD

**Issue by ppamorim** [Swinject/Swinject#384]
Hi,

I am getting the error `cannot assign to property: 'instance' is a get-only property` when I try to do something like this:
```swift
self?.playbackManager?.instance.playbackDelegate = self
```

Impl:
```swift
protocol PlaybackManager {
  var playbackDelegate: PlaybackDelegate? { get set }
}
```

This is happening probably because the function `instance` does this:

```swift
if let instance = _instance { /... }
```

Making the instance immutable, it should be a var or use force unwrap.

Version: v2.5.0
Swift 4.2

**Comment by jakubvano** [comment]
This is happening, because compiler infers that `PlaybackManager` is a value type. Declaring that `PlaybackManager` is a reference type should solve this issue:
```
protocol PlaybackManager: AnyObject {}
```

**Comment by ppamorim** [comment]
@jakubvano Thank you.
