### ISSUE TITLE
Missing registration if resolved immediately after lazy load assembly

### ISSUE THREAD

**Issue by sprynmr** [Swinject/Swinject#387]
I have a situation where I'm trying to register a few assemblies for a sample app to test my framework, one which depends on another framework that I need to mock:

```
MyContainer.shared.assembler.apply(assemblies: [MockAnalyticsProvidingAssembly(), UserSessionModule.assembly])
```

If I attempt to resolve one of the protocols in module B (UserSessionModule) right after this `.apply` call, it starts to run the closure but doesn't find the needed registration from module A (MockAnalyticsProvidingAssembly) inside the resolution closure.

```
self.userSessionLifecycleHelper = MyContainer.shared.resolver.resolve(UserSessionLifecycleHelper.self)
```

```
container.register(UserSessionLifecycleHelper.self) { (r) -> UserSessionLifecycleHelper in
    let userSessionState = r.resolve(UserSessionState.self)!
    let registrationSessionState = r.resolve(RegistrationSessionState.self)!
    let userSessionDispatcher = r.resolve(ActionDispatcher<UserSessionAction>.self)!
    let analyticsProvider = r.resolve(UserSessionAnalyticsProviding.self)! // failing here
    return UserSessionLifecycleHelper(appLifecycleEvents: NotificationCenter.default, userSessionState: userSessionState, registrationSessionState: registrationSessionState, userContextActionDispatcher: userSessionDispatcher, analyticsProvider: analyticsProvider, legacyCredentialsStorage: LegacyCredentialsStorage())
}
.inObjectScope(.container)
```

If I wrap the resolution in an `DispatchQueue.main.async{}` it works properly.

```
DispatchQueue.main.async {
    self.userSessionLifecycleHelper = SamsContainer.shared.resolver.resolve(UserSessionLifecycleHelper.self)
}
```

**Comment by sprynmr** [comment]
Update:

Wrapping it doesn't always resolve it. Most of the time it still fails. Curious if this is still related to that swift 4.2 compiler change to resolving types?

**Comment by sprynmr** [comment]
Sure. 

v2.5.0

Here's the registration. The `MockAnalyticsProvider` is just a `class` with a bunch of empty functions. However we also see the same issue if we use the legit class instead of the mock class. 

Not sure if it could be due to the protocol itself: `UserSessionAnalyticsProviding` which is a combination of a couple other protocols: `public protocol UserSessionAnalyticsProviding : CaptchaAnalyticsProviding, LoginAnalyticsProviding, ForgotEmailAnalyticsProviding, RegistrationAnalyticsProviding`

All those requirements are just very simply functions though like: `func trackTappedCallUsEvent()
`

```
class MockAnalyticsProvidingAssembly: Assembly {
    func assemble(container: Container) {
       container.register(UserSessionAnalyticsProviding.self) { (r) -> UserSessionAnalyticsProviding in
            return MockAnalyticsProvider()
        }
        .inObjectScope(.container)
    }
}
```

**Comment by jakubvano** [comment]
The fact that `UserSessionAnalyticsProviding` is a composed protocol should have no effect on this. AFAICS you are not doing anything suspicious 🤔, I'm not sure what could be causing the problem... 
Have you verified that `assemble` methods of those assemblies are called properly before `resolve`?

**Comment by dwsjoquist** [comment]
I created an extremely stripped down version of our project (I work with Bob) that demonstrates the problem: https://github.com/ivygulch/SwinjectResolveProblem

It acts like a class loader problem from my java days. The instance of the dependency is in the `services` dictionary inside the container. From the debugger, it appears like it should resolve, but the line `if let entry = services[key] {` in Container.getEntry(...) fails.

**Comment by dwsjoquist** [comment]
fwiw: I've also seen a similar problem between our main app target & the unit test target, so it isn't just in our sample app

**Comment by jakubvano** [comment]
When I run your sample project, I see:
> Class _TtC15AnalyticsModule28UserSessionAnalyticsProvider is implemented in both /Users/jakubvano/Library/Developer/Xcode/DerivedData/UserSessionModule-farqklrpbstshsbdttbbievnnwya/Build/Products/Debug-iphonesimulator/UserSessionModule.framework/UserSessionModule (0x103d9f7d8) and /Users/jakubvano/Library/Developer/CoreSimulator/Devices/7269374A-8C77-4378-8C88-7EF182E120BF/data/Containers/Bundle/Application/70EDEC61-7834-4CFA-A4FC-38AE7BDB86B3/UserSessionSampleApp.app/UserSessionSampleApp (0x103a18798). One of the two will be used. Which one is undefined.

This indicates to me, that there is some build settings / linking problem which results in the duplicate symbols: `UserSessionAnalyticsProviding` registered in the `AppDelegate` (via `AnalyticsModule.assembly`) is a different from `UserSessionAnalyticsProviding` resolved in the `UserSessionModule`.

This issue got resolved when I removed  `s.static_framework = true` from `AnalyticsModule.podspec`, and also `resolve` call works as expected after this change. I don't have enough experience with static cocoapods frameworks to help you there, but hopefully you can find a configuration that works for your project.

**Comment by dwsjoquist** [comment]
Thanks for taking a look!

**Comment by sprynmr** [comment]
Huh. Ok. So perhaps we are doing our cross target dependency stuff wrong in sample apps / unit tests. Thanks!
