### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by RiteshAdulkar** [Swinject/Swinject#392]
I am using **Xcode 10.2 beta3**, while running an app it showing `Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler` on import `Swinject`. I tried to update from `cathlog`,  following with command 'carthage update --plateform iOS --no-use-binaries', but it gets failed with exit code 65. tried clean and build but not woked.
In my cartfile-`github "Swinject/Swinject"
                         github "Swinject/SwinjectStoryboard"`

What's going wrong here, not able to figur out.

![screenshot 2019-03-06 at 3 57 20 pm](https://user-images.githubusercontent.com/4546577/53881190-fe482d00-4038-11e9-8b0f-633e7f31586e.png)

**Comment by jakubvano** [comment]
Swinjet is not yet compatible with Xcode 10.2 / Swift 5. There is work in progress at #391

**Comment by RiteshAdulkar** [comment]
yeah got the point. I downgraded the Xcode version, which is compatible with Swift 4.2.

**Comment by 1ucas** [comment]
Hello, is this issue still happening? 
If not, should we close it?

**Comment by yoichitgy** [comment]
Our latest release supports Swift 5. Let's close this issue. If we still see the issue, feel free to re-open it 👍
