### ISSUE TITLE
Runtime issue on Xcode 10.2

### ISSUE THREAD

**Issue by pffan91** [Swinject/Swinject#395]
Updated Xcode to the latest version 10.2. Swinject and SwinjectStoryboard added via CocoaPods. When I run my App I receive crash with this log in console:

objc[22164]: Swift class extensions and categories on Swift classes are not allowed to have +load methods

**Comment by jakubvano** [comment]
This is related to the SwinjectStoryboard, see https://github.com/Swinject/SwinjectStoryboard/pull/114
