### ISSUE TITLE
SwinjectStoryboard memory leaks

### ISSUE THREAD

**Issue by roei46** [Swinject/Swinject#396]
Hi guys,
So after a while i have checked for leaks using the debug memory graph and so that i have a few from the SwinjectStoryboard.
![Screen Shot 2019-04-01 at 17 13 55](https://user-images.githubusercontent.com/19977976/55334631-49bbf280-54a2-11e9-8e64-5de3232e05d6.png)
![Screen Shot 2019-04-01 at 17 13 39](https://user-images.githubusercontent.com/19977976/55334633-49bbf280-54a2-11e9-9259-4ec14449ade8.png)

The code i am using is ass follow : 
![Screen Shot 2019-04-01 at 17 20 36](https://user-images.githubusercontent.com/19977976/55334737-7b34be00-54a2-11e9-9a20-b5f0a4c6be5e.png)

And in the app delegate:
![Screen Shot 2019-04-01 at 17 21 13](https://user-images.githubusercontent.com/19977976/55334770-9273ab80-54a2-11e9-8017-8ac4b423935f.png)
Am i doing something wrong?  or is it a bug?
Thanks!

**Comment by jakubvano** [comment]
Have you confirmed that it is an actual leak (VC not deallocating, increased memory consumption, ...), or is it based solely on the analyser? Cause it has been known to produce false positives - see e.g. [this](https://github.com/Swinject/Swinject/issues/352#issuecomment-404240543)

**Comment by roei46** [comment]
In this case the VC is the initial root. so it wont dealloc and increased memory consumption is not the supposed to be(have one network call and it is with [weak self]).
I  started a side project to recreate the issue and i can see it also there.
I think the are 2 options:
1. Maybe i  am using swinject the wrong way 
2. Just maybe there is a leak in the pod?
If needed more code snippets i will provide.
Thanks!

**Comment by roei46** [comment]
So after testing i think it is confirmed.
The SplashViewController is deallocated.
I will also say that i am basing it using the instruments and the debug memory graph
![Screen Shot 2019-04-02 at 14 13 47](https://user-images.githubusercontent.com/19977976/55398571-8c88d380-5551-11e9-84f8-784ff1fbda11.png)
Any ideas ?

**Comment by jakubvano** [comment]
Are you by any chance able to isolate the leaky behaviour to some example project? It would be quite difficult to help without something concrete to play around with

**Comment by roei46** [comment]
Sure mate!
I will recreate it in a new small project.
Where do you want me to upload it?

**Comment by jakubvano** [comment]
Github repo should be fine 😉

**Comment by roei46** [comment]
Will do ASAP :)

**Comment by roei46** [comment]
Tell me if that works for you:
https://github.com/roei46/RetainTest.git

**Comment by jakubvano** [comment]
It works 👍 How can I simulate the leak?

**Comment by roei46** [comment]
Just run it and then press on the Debug memory Graph.
You will se the following image:
![Screen Shot 2019-04-07 at 10 39 05](https://user-images.githubusercontent.com/19977976/55680379-6aac9980-5921-11e9-9d51-052fbad882d2.png)
Tell me if it isn't simulating.

**Comment by jakubvano** [comment]
In this case `SpashViewController` was instantiated twice: Once from your code in `AppDelegate`, and second time by implicit storyboard instantiation - you have it turned on here:
![Screenshot 2019-04-08 at 09 10 01](https://user-images.githubusercontent.com/2094466/55705101-46fb5900-59de-11e9-9e68-d6292ddf8804.png)

Once you disable implicit storyboard, leak disappears.

**Comment by roei46** [comment]
Sorry for the delay, will check it first thing in the morning !
