### ISSUE TITLE
When .inObjectScope instance is resolved inside .initCompleted, there are temporarily two instances created

### ISSUE THREAD

**Issue by vol24pl** [Swinject/Swinject#398]
```swift
import Swinject

let container = Container()

protocol FooProtocol {}

protocol BarProtocol {}

class Foo: FooProtocol {
    var bar: BarProtocol?
}

class Bar: BarProtocol {
    let foo: FooProtocol

    init(foo: FooProtocol) {
        self.foo = foo
    }

    deinit {
        print("This print shouldn't happen")
    }
}

container.register(FooProtocol.self) { resolver in
    return Foo()
    }.inObjectScope(.container).initCompleted { resolver, foo in
        let foo = foo as! Foo
        foo.bar = resolver.resolve(BarProtocol.self) as! Bar
}

container.register(BarProtocol.self) { resolver in
    let foo =  resolver.resolve(FooProtocol.self)!
    let bar = Bar(foo: foo)
    return bar
    }.inObjectScope(.container)


let myBar = container.resolve(BarProtocol.self)!
```

This code will create two `Bar` instances and instantly deinit one of them. Shouldn't it check if there ~is~ will be an actual instance `inObjectScope` ~already~ created? Not sure if this problem is solvable.

**Comment by vol24pl** [comment]
1. You create a first `Bar` (first Bar doesn't exist)
2. inside it's `init` you make first `Foo` (first Bar doesn't exist, first Foo doesn't exist)
3. First `Foo` completes initialization and triggers `initCompleted` (first Bar doesn't exist, first Foo exist)
4. Inside `initCompleted` it created second `Bar` (first Bar doesn't exist, first Foo exist, second Bar doesn't exist)
5. Second `Bar` injects first `Foo` as it exists already (first Bar doesn't exist, first Foo exist, second Bar doesn't exist)
6. End of second `Bar`'s `init`. Second `Bar` created (first Bar doesn't exist, first Foo exist, second Bar *does* exist)
7. End of `initCompleted` for first Foo (first Bar doesn't exist, first Foo exist, second Bar *does* exist)
8. End of first `Bar`'s init (first Bar *does* exist, first Foo exist, second Bar *does* exist)

So my question is: `myBar` gets the reference to which one? 1st or 2nd `Bar`?

**Comment by jakubvano** [comment]
We are aware of the behavior (see [docs](https://github.com/Swinject/Swinject/blob/master/Documentation/CircularDependencies.md#remark)). We have tried to solve this issue (#134) but it proved to be a lot more complicated, so we ended up reverting the change (#164) - you can find discussion & reasoning in #159

**Comment by vol24pl** [comment]
I didn't looked at the "Remark" section in documentation, sorry! Thanks for taking your time to answer in such a detailed manner :)

Anyway which instance is injected? The "inner" or "outer" one?

I think the issue can be closed :)

**Comment by jakubvano** [comment]
If I remember correctly, it should be the "outer" one, but I wouldn't take my word for it 😄 Should be easy enough to check though.
