### ISSUE TITLE
Swinject: Resolution failed and Available registrations...  

### ISSUE THREAD

**Issue by roei46** [Swinject/Swinject#402]
Hi guys,
So just wanted to verify if i have a bug or this is a normal behaviour of SwinjectStoryboard.
So i get this prints:

Swinject: Resolution failed. Expected registration:
	{ Service: UIViewController, Storyboard: UINavigationController, Factory: (Resolver, UIViewController) -> UIViewController }
Available registrations:
	{ Service: UIViewController, Storyboard: InstallerApp.LoginViewController, Factory: (Resolver, UIViewController) -> UIViewController, ObjectScope: graph, InitCompleted: Specified 1 closures }
	{ Service: UIViewController, Storyboard: InstallerApp.CameraStatusViewController, Factory: (Resolver, UIViewController) -> UIViewController, ObjectScope: graph, InitCompleted: Specified 1 closures }
	{ Service: UIViewController, Storyboard: InstallerApp.ChooseCameraViewController, Factory: (Resolver, UIViewController) -> UIViewController, ObjectScope: graph, InitCompleted: Specified 1 closures }

and my classes looks like this:

![Screen Shot 2019-05-13 at 16 07 22](https://user-images.githubusercontent.com/19977976/57623808-3fa90b80-7599-11e9-88b5-1357dcf3dec2.png)
![Screen Shot 2019-05-13 at 16 07 06](https://user-images.githubusercontent.com/19977976/57623809-3fa90b80-7599-11e9-8179-d30bd38fa9c1.png)

Would love to hear if the problem is on me :)

Thanks!

**Comment by jakubvano** [comment]
It is a known issue with interaction between failure logging & swinject storyboard, see #213

**Comment by roei46** [comment]
Oh, didn't see that.
Any solution as to this time?

**Comment by jakubvano** [comment]
There has been no update / fix for this behaviour yet - your best bet as of now is probably to disable logging / implement custom logging function
