### ISSUE TITLE
Question: Resolve Dependency with initial argument, and retrieve it later without argument. 

### ISSUE THREAD

**Issue by miguel-jimenez-0529** [Swinject/Swinject#408]
Hi guys, what a great project you have here. I've been using it and is fascinating.

I have one question, and I wonder if you could help me out. 

I'm using 'Swinject', '~> 2.6.0'

I have registered a Dependency which needs an argument, so the first time I need it I pass the argument and everything works fine. But later on, I need the same instance of the Dependency but I don't have access to the argument any more but I would like to get the instance of the dependency that the Swinject Container has. Is there a way to do this?

By trying to resolve it without the argument I get this error.

Swinject: Resolution failed. Expected registration:
	{ Service: MyDependency, Factory: Resolver -> MyDependency }
Available registrations:
	{ Service: MyDependency, Factory: (Resolver, Argument) -> MyDependency, ObjectScope: weak }

**Comment by jakubvano** [comment]
This does not look like a job for a DI layer - relying on the order of the `resolve` invocations seem like a very fragile practice. I would recommend implementing this reuse logic in application code.

However, if you really wanted to you could take an advantage of the fact, that Swinject does not care about the values of arguments when reusing instances:
```
// assuming that .any is some value of the argument
container.register(MyDependency.self) { $0.resolve(MyDependency.self, argument: Argument.any)!  }

var d1 = container.resolve(MyDependency.self, argument: Argument())
var d2 = container.resolve(MyDependency.self)
d1 === d2
```

**Comment by miguel-jimenez-0529** [comment]
Thanks for the answer @jakubvano, what you mentioned is exactly what I'm trying to do, unfortunately, I get the error that I described in my initial comment. Also as you mentioned what I'm trying to do may not be a good practice,  so I'll try to implement it in the application code.
