### ISSUE TITLE
EXC_BAD_ACCESS when resolving on background thread

### ISSUE THREAD

**Issue by drekka** [Swinject/Swinject#411]
Been getting regular crashes when resolving on a background thread.
 It appears that when the resolve occurs, the `currentObjectGraph` is nil. See attached screen dump. 

Any idea how to get past this (apart from working on the main thread :-)

<img width="1391" alt="Screen Shot 2019-06-03 at 9 57 46 pm" src="https://user-images.githubusercontent.com/153837/58800250-af675f00-864a-11e9-8a31-e2d520fd74ac.png">

**Comment by drekka** [comment]
My bad. Wasn't using synchronised resolvers. Could I suggest adding a message to the fatal asking if this could be the situation.

**Comment by jakubvano** [comment]
Adding a suggestion to the crash is a good idea 👍
