### ISSUE TITLE
SPM does not seem to work

### ISSUE THREAD

**Issue by alexbredy** [Swinject/Swinject#415]
Hi All,

In the context of a server side project, I have added a couple of dependencies, including Swinject. `swift build` hangs indefinitely when trying to add Swinject as a dependency whereas it works correctly for all the other packages installed.

The dependency was added as such in my `Package.swift`:

`.package(url: "https://github.com/Swinject/Swinject.git", from: "2.0.0")`

Any ideas or help is welcome :)

**Comment by jakubvano** [comment]
Thanks for pointing it out - I don't have much experience with SPM, but issue sems to be with Swift tools version: Swinject's package description is still in `3.1.0` which is no longer supported.

Will try to fix this ASAP

**Comment by jakubvano** [comment]
Should be fixed by #414, released with `2.6.2`
