### ISSUE TITLE
currentObjectGraph is deleted before it's resolving isn't completed

### ISSUE THREAD

**Issue by zSOLz** [Swinject/Swinject#417]
Hello!
I have crash at `guard let currentObjectGraph = currentObjectGraph else { fatalError() }` when I'm trying to resolve cascade dependencies. The problem is child container completes resolution graph for itself and for it's parent as well while parent did not finish resolving all dependencies.
The sample code to reproduce this issue is here:
```
class A {}
class B {}
class C {}

let container = Container()
let childContainer = Container(parent: container)

container.register(A.self) { resolver in
    let c = childContainer.resolve(C.self)! // resolve 'C' and delete main container graph
    let b = resolver.resolve(B.self)! // fatal error here
    return A()
}
container.register(B.self) { _ in B()  }
childContainer.register(C.self) { _ in C() }

let a = container.resolve(A.self)!
```
The issue was taken place after https://github.com/Swinject/Swinject/pull/409 when `graphResolutionCompleted()` call was added for parent as well.

**Comment by jakubvano** [comment]
What is the reason for calling `childContainer` directly in the `register` closure? Maybe your usecase could be achieved in a more idiomatic way? I'd say that it is a misuse of the API - one should not invoke specific container, but rely on the passed `resolver` instead.

**Comment by zSOLz** [comment]
Thanks for the answer! The sample was oversimplified.
> What is the reason for calling `childContainer` directly in the `register` closure?
We started using Swinject before `Assembler` class was introduced and we created own modular mechanism. Each module contains own container. So, sometimes during resolving process it's needed to resolve not dependencies, but whole module with own container and dependencies. When class A requires some external module, witch can resolve C class.
```
let container = Container()
container.register(ModuleC.self) { [unowned container] _ in
     return ModuleC(parent: container) // register module with class C
}
container.register(A.self) { resolver in
    let moduleC = childContainer.resolve(ModuleC.self)!
    let c = moduleC.resolve(C.self)! // resolve 'C' and delete main container graph
    let b = resolver.resolve(B.self)! // fatal error here
    return A()
}
container.register(B.self) { _ in B()  }

let a = container.resolve(A.self)!
```

**Comment by jakubvano** [comment]
I see. I'd still consider this a misuse of the API, but it is quite easy to reimplement #409 without breaking your usecase, see #418
