### ISSUE TITLE
Bundle id Error

### ISSUE THREAD

**Issue by raptorxcz** [Swinject/Swinject#432]
**Describe the bug**
Report from Apple:
ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'com.el-eleven.Swinject' is used in the bundles '[Swinject.framework, Swinject.framework]'
App have iOS and watchOS target.

**To Reproduce**
1. make app with multiple platforms
2. upload it to AppStore

**Expected behavior**
No error from Apple

**Environment:**
 - Xcode version: Xcode 10.3
 - Swift version: 5.0.1
 - OS running SWXMLHash: MacOS 10.14.6 running Xcode

**Additional context**
Add `.${PLATFORM_NAME}` to end of bundle id

**Comment by jakubvano** [comment]
Resolved by #433, released in 2.7.0
