### ISSUE TITLE
Slack channel link is dead

### ISSUE THREAD

**Issue by sschilli** [Swinject/Swinject#438]
I'd like to discuss a few things in the Slack channel but the link is dead and I can't find one anywhere else.

**Comment by marciniwanicki** [comment]
+1, would be great to update it or remove if it's not longer active

**Comment by bdrobert** [comment]
+1

**Comment by yoichitgy** [comment]
I was thinking to fix the link using [slack-invite-automation](https://github.com/outsideris/slack-invite-automation) service, but it is no longer available for a Free plan of Slack.

To get slack-invite-automation working, `admin.users.invite` Slack API should be accessible, but it is available for only Enterprise account.
https://stackoverflow.com/questions/62902933/is-there-a-way-i-can-invite-users-to-my-slack-workspace-through-the-slack-api-fo

It might be good to use Slack only for some reminders/communication for maintainers, and use GitHub issues, Twitter or something that are open to anyone.

**Comment by yoichitgy** [comment]
Removed the link to the Slack workspace in PR #491.
