### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by shayan-dnsh** [Swinject/Swinject#448]
public func setInstance(_ instance: Any?, inGraph graph: GraphIdentifier) {
        self.instance = instance

        if instances[graph] == nil {  // Thread 8: EXC_BAD_ACCESS (code=EXC_I386_GPFLT) Happened Hear and instance is DisposeBag
            instances[graph] = Weak()
        }
        instances[graph]?.value = instance
    }

**Comment by trujamal** [comment]
Also getting this error in my project any updates to this?

**Comment by chulunus** [comment]
I too am having this same issue and wondering if there is any updates.

**Comment by SJLGarin** [comment]
我也遇到了，有暂时避免此崩溃的方法吗

**Comment by maksirol** [comment]
Hello, any update to this issue or workaround?

**Comment by KamilGucik** [comment]
Hello, any updates?

**Comment by Telinir** [comment]
Should be addressed, make sure to use a synchronized container to avoid this as this is primarily a concurrency issue
- #523

**Comment by maxim-chipeev** [comment]
Should be addressed, make sure to use a synchronized container to avoid this as this is primarily a concurrency issue
- #523
