### ISSUE TITLE
No such module in xcode 11.4

### ISSUE THREAD

**Issue by sudansh** [Swinject/Swinject#449]
Unable to build
Xcode version: 11.4
using carthage
Swinject version (or git SHA) : 
The steps to reproduce the issue:
Add Swinject to any project and try to build. 
error: `No such module: Swinject`

**Comment by rojanDinc** [comment]
I am also having this problem. Commenting out `use_frameworks!` in the Podfile makes Xcode finding it but it breaks other things.

**Comment by 1ucas** [comment]
Hello everyone! 

My name's Lucas and I've been recently added to the Swinject Organization to help addressing some issues.

Is it still happening today, or it was a specific bug in Xcode 11.4? 

Also, it would help a lot if you could tell us the Swinject version you're using.

**Comment by sudansh** [comment]
Closing this as I have updated the xcode and can't follow up if this bug still exists
