### ISSUE TITLE
Long Term Support

### ISSUE THREAD

**Issue by davidthorn** [Swinject/Swinject#452]
I have recently been informed about Swinject by other colleges. I do however see that it's been some time since any commits have been made.

Could one of the contributors confirm that this library will be supported over the next coming years.

Thanks

**Comment by uditsalwan** [comment]
Hi Team.. Does anyone have a roadmap for future support and updates?

**Comment by Prince2k3** [comment]
I think this repo is no longer maintained.

**Comment by davidthorn** [comment]
I would be happy to assist with maintaining this repository if someone could add me.

**Comment by codeman9** [comment]
@davidthorn Fork and rename? This is my favorite DI container library for swift and it would be a shame to lose it.

**Comment by Prince2k3** [comment]
@codeman9 Thats not a bad idea. I would love updates with this library especially with SwiftUI

**Comment by geraldeersteling** [comment]
I've been looking at alternatives like Weaver or Needle, does anyone have good recommendations? I feel like Swinject is becoming more and more desolated...

**Comment by claymation0x0** [comment]
Cleanse by square is good and looks maintained https://github.com/square/cleanse

**Comment by geraldeersteling** [comment]
Yeah, I've been looking into Cleanse as well. It's pretty complex, looks maintained for now though

**Comment by Prince2k3** [comment]
The closest to Swinject I've seen is Resolver. 

https://github.com/hmlongco/Resolver

**Comment by geraldeersteling** [comment]
Resolver actually looks great as well! I'm going to try and switch to that one instead of Cleanse since I'm encountering a problem with a dependency cycle. Thanks for pointing these out, keep 'em coming 😄

**Comment by tkohout** [comment]
@davidthorn Thanks for opening this. I am only a member so I can't add more people into the team. I am trying to reach the admins to see if they can bring some more people into the project.

**Comment by davidthorn** [comment]
@tkohout That's super, look forward to seeing what the result is!

**Comment by yoichitgy** [comment]
Thanks @tkohout and @davidthorn. I invited tkohout to Swinject team. For now, I don't have much time to maintain the project. It's really helpful if you update Swinject to follow the latest Swift/iOS versions🙏

**Comment by davidthorn** [comment]
> Thanks @tkohout and @davidthorn. I invited tkohout to Swinject team. For now, I don't have much time to maintain the project. It's really helpful if you update Swinject to follow the latest Swift/iOS versions🙏
> 
> I'll give information about releases (such as CocoaPods) later.

Thanks, I will try my hardest to allocate some of my time per month to this project.
