### ISSUE TITLE
Is SpinLock actually a spin lock?

### ISSUE THREAD

**Issue by macdrevx** [Swinject/Swinject#459]
[`SpinLock`](https://github.com/Swinject/Swinject/blob/master/Sources/SpinLock.swift) seems like a misleading name because under the hood, it's using `NSRecursiveLock` which, as far as I can tell, is a blocking lock.

Mike Ash, writing about a list that includes `NSRecursiveLock`, [states](https://www.mikeash.com/pyblog/friday-qa-2017-10-27-locks-thread-safety-and-swift-2017-edition.html):

> I mentioned spinlocks as one type of lock, but none of the APIs listed here are spinlocks.

Apple's synchronization guide [states](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/ThreadSafety/ThreadSafety.html) about spin locks:

> The system does not provide any implementations of spin locks because of their polling nature, but you can easily implement them in specific situations.

**Comment by macdrevx** [comment]
Looks like it used to actually be a spin lock. When it was [refactored](https://github.com/Swinject/Swinject/commit/499c58ac3a5f81b3fc2208fddb3573a4de55f50d#diff-058cae0d02157ab70b65495d4fcb0147) to use NSLock, it wasn't renamed.

**Comment by macdrevx** [comment]
Seems like at this point a better name would just be `RecursiveLock`

**Comment by yoichitgy** [comment]
Thanks @macdrevx for providing the correct definitions and researching the past context!😃

It took long time to respond, but it looks good to me to take your suggestion to rename it to `RecursiveLock`👍
