### ISSUE TITLE
Travis CI not posting status to pull requests

### ISSUE THREAD

**Issue by tkohout** [Swinject/Swinject#463]
Seems like something has broken with the CI builds. They are being triggered and successfully complete but the result is not being posted to the Github.

According to [this issue](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798) It might require to migrate the Travis to .com repositories. 

Someone with admin rights have to do it though. @jakubvano @yoichitgy ?

**Comment by yoichitgy** [comment]
Sorry I didn't respond for long time. Thankfully, @1ucas will take the CI migration👏

We are still not sure which travis-ci.com or GitHub Actions are better for our open source project to migrate to. 1ucas will take some research😃

**Comment by 1ucas** [comment]
Hello!!! That's it Yoichi! 
I'm working on it!
And I hope to have more updates soon!
