### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by iamszabo** [Swinject/Swinject#469]
This framework is awesome, I use it on every project but I'm wondering if the project is dead as there has been no new release for 2 years now.

**Comment by SaezChristopher** [comment]
I think we should fork it and maintain it .

**Comment by karthikAdaptavant** [comment]
+1

**Comment by 1ucas** [comment]
@SaezChristopher , there are 365 forks already..... I wonder if anyone of those are still being updated.

**Comment by jakekrog** [comment]
@yoichitgy any thoughts on the current state of Swinject and its future?

**Comment by ChediB** [comment]
+1

**Comment by bartguminiak** [comment]
+1

**Comment by mpdifran** [comment]
Hey everyone! I agree that this project is important! 

I was recently added to the Swinject organization, so I can definitely help merge in changes and perform releases if there's stuff missing. Currently on my radar is adding XCFramework support for Carthage, and I've also been playing around with some DocC stuff https://github.com/Swinject/Swinject/pull/471. 

Please let me know what you'd like to add and I'll make sure it gets in!

**Comment by yoichitgy** [comment]
Hi everyone. Sorry I was away from the project for long time and didn't notice this issue.

As @mpdifran said, he kindly joined the project. We still think it would be nice to have more people to maintain Swinject. If you are interested in being a maintainer, please let me know in this issue thread or DM me on [Twitter](https://twitter.com/yoichitgy)🙏

Thanks!

**Comment by 1ucas** [comment]
Hello,
I don't have much free time during the week. 
But if I can help somehow, you can count me in.

**Comment by yoichitgy** [comment]
Thanks @1ucas😃 I invited you to our Slack group. Would you check your email on gmail to join there?

**Comment by 1ucas** [comment]
Thanks!

**Comment by 72A12F4E** [comment]
> Hi everyone. Sorry I was away from the project for long time and didn't notice this issue.
> 
> As @mpdifran said, he kindly joined the project. We still think it would be nice to have more people to maintain Swinject. If you are interested in being a maintainer, please let me know in this issue thread or DM me on [Twitter](https://twitter.com/yoichitgy)🙏
> 
> Thanks!

I’d love to assist, in a maintainer role or otherwise! 😄

**Comment by yoichitgy** [comment]
We made a kanban board `Maintained/Maintenable Again😃` as our actions to get Swinject maintained/mainenable again.
https://github.com/Swinject/Swinject/projects/1

**Comment by 72A12F4E** [comment]
> Thank you @72A12F4E for your offer to assist the project👍 I really appreciate your offer😃😃😃
> 
> One thing I have to say is I do not see your GitHub or online activity as a developer so much. I really respect your offer, but would you start from a contributor to the project before being a maintainer if you do not mind? 🙏🙇
> 
> Issues #474 or #475 look good as the first step if you are interested. Would you let me know your opinion?🙏

I completely understand; most of my focus has been at my job which doesn't use GitHub. I'll see what I can do to knock out those two issues.

**Comment by yoichitgy** [comment]
Thank you @72A12F4E for understanding😃

I agree a lot of experienced engineers focus on jobs and use GitHub less. I'm looking forward to inviting you as a maintainer soon🚀

**Comment by yoichitgy** [comment]
We made a new release. Thanks @mpdifran and @1ucas for working together!
https://github.com/Swinject/Swinject/releases/tag/2.8.0
