### ISSUE TITLE
Can't open playground with Xcode 7.2

### ISSUE THREAD

**Issue by gilroykilroy** [Swinject/Swinject#47]
When you open the project none of the SDK's are set in any of the targets. When you set them correctly and try to build the project it says PRODUCT_NAME undefined. I set that to Swinject then it spits out:

Umbrella header 'Swinject.h' not found,
Could not build Objective-C module 'Swinject'

What now?

**Comment by yoichitgy** [comment]
Would you attach a screenshot of the error messages?

Here is an instruction to run the playground:
https://github.com/Swinject/Swinject#play-in-playground

You need to build `Swinject-iOS` target like this image before running the playground:

<img width="747" alt="screen shot" src="https://cloud.githubusercontent.com/assets/965994/12106497/b08847be-b3a3-11e5-92b8-fb245f235bd5.png">

**Comment by gilroykilroy** [comment]
Hmmm. I tried it again and it compiled (after the fixes below):

Opening the project file right after git clone shows my Mac as the iOS target:





Changing the base SDK to Latest iOS and trying to compile



Setting the Product Name and compiling then worked

**Comment by yoichitgy** [comment]
That's good to hear you succeeded building the project.

It looks Xcode has the problem. Sometimes I have another (similar) problem on another project, and restarting Xcode or removing `DerivedData` solves the problem.
