### ISSUE TITLE
Fix inconsistency between Xcode project file and project.yml

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject#474]
We introduced [XcodeGen](https://github.com/yonaskolb/XcodeGen) with [project.yml](https://github.com/Swinject/Swinject/blob/master/project.yml) file, but it was not always used and now we have inconsistency between the Xcode project file and project.yml.

We would like to do the following to solve the current issue.
- Fix the inconsistency itself between the Xcode project file and project.yml.
- Introduce a way to keep consistency between the Xcode project file and project.yml. Maybe on CI or any other automated procedure to keep using XcodeGen.

**Comment by 1ucas** [comment]
1) I just fixed the first bullet. 
2) I can force the CI to update the project running at the pipeline. But that wouldn't fix the project at the repository.
The easiest way to keep consistency is to stop versioning it. 
Will that become a problem for Cocoapods users?
Before linting / publishing the podspec, the CI can generate a fresh project file.

**Comment by yoichitgy** [comment]
Thanks @1ucas a lot😃 I set the assignee to you on this issue🙏
