### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by ysholqamy** [Swinject/Swinject#48]
Hi, are you willing to add support for swift package manager anytime soon?

**Comment by yoichitgy** [comment]
Yes. I will support it soon. So far, I finished half things to do in my branch. Still I have to migrate unit test code to support it.

https://github.com/yoichitgy/Swinject/tree/source-layout

**Comment by yoichitgy** [comment]
It looks if *SwinjectStoryboard* directory is in *Sources* directory, *Sources* directory cannot have source files right under the directory. I tried moving those files to *Sources/Swinject* directory, but still I got a lot of errors.

Need more investigation...

**Comment by yoichitgy** [comment]
Will be available at v2.0.0-beta.2.
