### ISSUE TITLE
Fix release makefile to get the current branch in a way that supports older git versions

### ISSUE THREAD

**Issue by mpdifran** [Swinject/Swinject#486]

**Comment by 1ucas** [comment]
I still have the same doubt. Shouldn't it (the makefile) be a workflow at the CI, in a way it doesn't depend on each developer's environment?

**Comment by mpdifran** [comment]
If it's easy enough to do it through CI, then we can jump straight there. I was figuring this would be an easy first step that would help make releases easier, and we can integrate into CI as a phase 2.

**Comment by 1ucas** [comment]
That a look at this Pull Request. It has almost all step.
But I didn't know it would be worth it to invest more time.
https://github.com/1ucas/Swinject/pull/3/files

**Comment by yoichitgy** [comment]
That's nice! Thanks 1ucas!

**Comment by mpdifran** [comment]
@yoichitgy I believe you've made some updates in this area, should this task be closed?

**Comment by yoichitgy** [comment]
@mpdifran I noticed fixing our Makefile was insufficient and made the following PRs.

- https://github.com/Swinject/Swinject/pull/495
- https://github.com/Swinject/SwinjectStoryboard/pull/167

Would you review them? After merging them, we can close this issue👍

I think the release process using CI/CD (GitHub Actions) can be another (next step) issue.

**Comment by mpdifran** [comment]
Reviewed and merged! I'll close this issue now.
