### ISSUE TITLE
FR: Enable library evolution support 

### ISSUE THREAD

**Issue by jesus-mg-ios** [Swinject/Swinject#488]
## Problem
Framework is not enable for evolution support.
So for example, Xcode showed up this kind of errors:

<img width="393" alt="Swift module cannot be imported" src="https://user-images.githubusercontent.com/85997060/125260936-17e09a00-e301-11eb-850d-1144619deec0.png">

## Feature Request

> Xcode
> When using Xcode to develop for Apple platforms, set the BUILD_LIBRARY_FOR_DISTRIBUTION build setting in the framework’s target. This setting turns on both library evolution and module stability. Be sure to use the setting in both Debug and Release builds.
> 
> The BUILD_LIBRARY_FOR_DISTRIBUTION Xcode build setting and associated .xcframework support were presented at WWDC 2019 in the talk titled Binary frameworks in Swift.
[https://swift.org/blog/library-evolution/](swift.org)

Set BUILD_LIBRARY_FOR_DISTRIBUTION value to YES in configurations.

@yoichitgy

**Comment by 1ucas** [comment]
Hello! 

Thanks for reporting the issue. 

I'll take a look at this.
