### ISSUE TITLE
Breaking change with Swinject 2.8.0

### ISSUE THREAD

**Issue by Nakwendaa** [Swinject/Swinject#498]
Hi,

Swinject 2.8.0 introduced a breaking change by setting minimum iOS deployment target to 9.0 (was 8 with 2.7.1).
From my point of view, if we respect semver, we should have release Swinject 3.0.0 instead of 2.8.0.
It caused that we're unable to compile SwinjectAutoregistration today because it depends Swinject ~> 2.7.

I don't know if it is possible, but i think we should remove 2.8.0 podspec and release a 3.0.0.

**Comment by 1ucas** [comment]
Hello, Nakwendaa. 
Thanks for you feedback.
I'm sorry to hear that.

I'm talking to the maintainers about this situation.
