### ISSUE TITLE
Support watchOS and tvOS

### ISSUE THREAD

**Issue by yoichitgy** [Swinject/Swinject#5]
Add watchOS and tvOS targets to the project to support them.

**Comment by jondwillis** [comment]
A colleague of mine indicated that there is an issue with Swinject and Xcode 7.1 beta 2 (Swift 2.1)

I've done this already in https://github.com/jondwillis/Swinject/blob/master/Swinject.podspec

**Comment by yoichitgy** [comment]
Thank you for trying Swinject with tvOS because I still didn't try. It looks I can merge the podspec later.

A problem here is supporting watchOS is not so straightforward because UIStoryboard class is not accessible in watchOS. I might split SwinjectStoryboard into another project, and might keep Swinject project as pure Swift code to easily modify the core features for all the targets (iOS, OSX, watchOS and tvOS).

In contrast, Supporting SwinjectStoryboard in tvOS looks ok.

**Comment by yoichitgy** [comment]
[Swinject version 0.2.3](https://github.com/Swinject/Swinject/releases/tag/0.2.3) supports watchOS.

**Comment by yoichitgy** [comment]
tvOS is supported in `xcode7.1` branch. To install Swinject with CococaPods or Carthage, specify the commit 6f55e9caae24dc059874a338b3be5086393f1f40 or later.

**Comment by yoichitgy** [comment]
@jondwillis, I didn't merge your commit but it was a good guidance to modify the podspec to support watchOS and tvOS. Thank you.

**Comment by yoichitgy** [comment]
Version 0.4 supports tvOS too.
