### ISSUE TITLE
EXCLUDED_ARCHS[sdk=iphonesimulator*]: 'arm64' causes error on M1Macbooks

### ISSUE THREAD

**Issue by gadireddi226** [Swinject/Swinject#500]
If we use swinject in our project and we need to use simulator on our M1 macbooks we are unable to build our project. 
Could you please get rid of the excluded architectures in future versions it does not make sense to exclude them in newest Xcode?

**Comment by willemfrishert** [comment]
@gadireddi226 I'm having the same issue and noticed that there's already a PR up for it. Have a look at https://github.com/Swinject/Swinject/pull/497

**Comment by gadireddi226** [comment]
Thanks for letting me know @willemfrishert . I hope they will merge it soon.
