### ISSUE TITLE
Checking for existing entries in a container

### ISSUE THREAD

**Issue by denisPoifol** [Swinject/Swinject#508]
## Introduction

Swinject enables to register services independently to what is already registered in the container.
This is great to some extend, but it raises the issue of trying to resolve something that has not been registered.

## Motivation

If I want to register a `ViewController` class I don't have to worry wether it dependencies have already been registered or not.
```
container.register(ViewController.self) { resolver in
    ViewController(serviceA: resolver.resolve(ServiceA.self)!)
}

container.register(ServiceA) { resolver in
    ServiceAImplementation()
}
```
This work perfectly and we can even go further and register our `ServiceA` in a separate `Assembly` if we want to.

As many project grow using Swinject one of two things might happen :
- Most service registration are done in the same place and it become hard to maintain and be sure that every entry will not eventually crash by trying to resolve something that is not registered or registered with different parameters.
- Services registrations are split in different Modules depending from one another, it is easier to maintain. But most module rely on another to provide an entry they require. In the end the risk of crashing still remains.

In both case service registration contains a lot of critical code with no way to test it.

## Proposed solutions

The issue is that there is no way to check for the existence of a service registration without trying to resolve it.

### Exposing a method on `Container` to check the existence of an entry

Adding to the `Container` API a `isServiceRegistered<Service, Arguments>(_ serviceType: Service.Type, arguments....)` would be an easy solution.
```
func isServiceRegistered<Service, Arguments>(_ serviceType: Service.Type, 
                                             _ arguments: Arguments,
                                             name: String? = nil,
                                             option: ServiceKeyOption? = nil) -> Bool {
    let key = ServiceKey(serviceType: Service.self, argumentsType: Arguments.self, name: name, option: option)
    return services.keys.contain(key)
}
```
###  Directly expose an immutable `Set` of `ServiceKey` in `Container` API

This way an `Assembly` can directly check the existence of any given key within the container it is registering into.

## Futur direction

To go even further we could enable an `Assembly` to define a set of *Entries* (or `ServiceKey`) required from the container it `assembles` in.

**Comment by asuzdaltsev** [comment]
You can use behavior to achieve this. In the behavior you can save the key in a collection and query for the key presence

**Comment by bradfol** [comment]
Looks like the method you proposed has been recently added in this PR https://github.com/Swinject/Swinject/pull/521. A release hasn't been cut yet so the change is not yet available but hopefully soon.

**Comment by denisPoifol** [comment]
Just seeing responses now.
Thanks a lot @bradfol 
Thanks @asuzdaltsev, also your solution would have required to manually store information that just was not accessible for no  good reason.
