### ISSUE TITLE
Unable to update to the latest version of Swinject as SwinjectStoryboard depends on an older version of Swinject

### ISSUE THREAD

**Issue by sskjames** [Swinject/Swinject#513]
SwinjectStoryboard depends on Swinject 2.7.1.
Since we use SwinjectStoryboard in our project, this has been blocking us from using the latest Swinject version.
There is an open issue [169](https://github.com/Swinject/SwinjectStoryboard/issues/169) highlighting this problem.
I'm creating this issue here in the hope that SwinjectStoryboard and Swinject might have some common maintainers.
Please take a look at it.

Thank you.
James

**Comment by mpdifran** [comment]
Thanks for the ticket, we'll take a look and fix this ASAP! Sorry for the delay.

**Comment by sskjames** [comment]
Hi @mpdifran, thank you for having a look at this issue. 
There is an [open PR ](https://github.com/Swinject/SwinjectStoryboard/pull/175) created by @BarredEwe to address this.

**Comment by mpdifran** [comment]
Merged! Thanks for the contribution.
