### ISSUE TITLE
Carthage: failed to build Swinject

### ISSUE THREAD

**Issue by Nikita2k** [Swinject/Swinject#52]
I have a Cartfile:
```
github "Swinject/Swinject" ~> 1.0.0
```
and running build: `carthage update --no-use-binaries --platform iOS`

Here is my build log:

```
carthage update --no-use-binaries --platform iOS
*** Fetching Swinject
*** Checking out Swinject at "1.0.0"
*** xcodebuild output can be found in /var/folders/xx/wdhyt54n6qg6tvxm21313qsxqqjp3v/T/carthage-xcodebuild.nDq8Y4.log
*** Building scheme "Swinject-iOS" in Swinject.xcodeproj
xcodebuild: error: Failed to build project Swinject with scheme Swinject-iOS.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'Swinject-iOS'.
A shell task failed with exit code 70:
xcodebuild: error: Failed to build project Swinject with scheme Swinject-iOS.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'Swinject-iOS'.
```
As you can see, for some reason it cannot be built on iPad2. I think issue is very similar to https://github.com/kif-framework/KIF/issues/650

**Comment by yoichitgy** [comment]
Hi. Which version of Carthage are you using? The issue is reported to not only KIF but also [a lot of projects](https://www.google.com/search?client=safari&rls=en&q=%22The+run+destination+iPad+2+is+not+valid+for+Running+the+scheme%22&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=8n-cVoqWKKeT8QeahIaAAw&gws_rd=cr&fg=1).

**Comment by Nikita2k** [comment]
My version is:
```
carthage version
0.8.0
```

**Comment by yoichitgy** [comment]
Please try 0.9.2 or later (the latest is 0.11.0), and let me know whether the issue is resolved. According to  [this issue report](https://github.com/SwiftyJSON/SwiftyJSON/issues/386), the problem looks to be resolved.

**Comment by Nikita2k** [comment]
Yes, seems to be not related to Swinject. With 0.11.0 builds as expected.
Thank you!
