### ISSUE TITLE
"master" branch is 🔥 DEAD 🔥

### ISSUE THREAD

**Issue by ukushu** [Swinject/Swinject#524]
Issues in GraphIdentifier

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/yKmzc.png

Even tests are failed:

[![enter image description here][2]][2]

  [2]: https://i.stack.imgur.com/C0cMb.png

**Comment by CezaryCiosek** [comment]
+1

**Comment by mpdifran** [comment]
Oh no, I'll take a look right away!

**Comment by maxim-chipeev** [comment]
Hi @ukushu, could you share a bit more about your dev-environment? This passed on Travis CI before but…it looks like Travis is disabled on the repo temporarily 😬

Does adding `import Foundation` resolve those errors?

**Comment by ukushu** [comment]
I have connect Swinject as package, so I cannot edit files and cannot add "import Foundation" :(

I have connected Swinject in few projects:
* Swinject connected as package
* macOs app
* written on swift

Fixed issue with switch to "2.8.1" version.

**Comment by maxim-chipeev** [comment]
@bradfol fixed this in #526, thanks!
