### ISSUE TITLE
Current deployment targets are not compatible with xCode 14.3

### ISSUE THREAD

**Issue by KarinBerg** [Swinject/Swinject#534]
**Problem:**

When using Swinject in a project which is build with xCode 14.3.x then you have to increase the deployment targets to at least:
iOS: 11
macOS: 10.13
tvOs: 11
watchOS: 4.0

So, could you consider to increase the deployment targets of Swinject?

**Comment by KarinBerg** [comment]
@yoichitgy, @mpdifran,@jakubvano, @tkohout, @davidthorn, @1ucas

Swinject is not compatible to xCode 14.3.x (>= iOS 11). Could you update the deployment targets for Swinject and SwinjectAutoregistration and release a new CocoaPod release???

This would be awesome :)

**Comment by mpdifran** [comment]
Thanks for bringing to our attention, I'll do a release after merging this in!

**Comment by mpdifran** [comment]
PR merged, and released under [2.8.4](https://github.com/Swinject/Swinject/releases/tag/2.8.4)! Thanks for the contribution!

**Comment by KarinBerg** [comment]
Thanks for releasing a new version of Swinject!!!

@mpdifran Do we also need a new release of SwinjectAutoregistration to make it campatible?
see https://github.com/Swinject/SwinjectAutoregistration/pull/89

**Comment by KarinBerg** [comment]
@mpdifran Swinject version 2.8.4 is not available on https://cocoapods.org/. Is there a step missing?
see https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by mpdifran** [comment]
@KarinBerg yes, I'm having trouble releasing to cocoapods. It's related to the new xrOS target for Vision Pro. I'll look into releasing `SwinjectAutoregistration` as well.

**Comment by KarinBerg** [comment]
@mpdifran Any new updates on Cocoapods release? Can I support you in any way?

**Comment by KarinBerg** [comment]
@mpdifran 
Sorry, for asking again. Any new updates on Cocoapods releases for Swinject and SwinjectAutoregistration? Can I support you in any way?

https://cocoapods.org/pods/Swinject
https://cocoapods.org/pods/SwinjectAutoregistration
