### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by FONickReichard** [Swinject/Swinject#542]
At WWDC23 Apple announced that apps and SDKs that make use of certain "required reason" APIs will need to provide a privacy manifest.

Is this update on the roadmap for the team? I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

Apple News:

https://developer.apple.com/news/?id=r1henawx 

Thank you

**Comment by kishorepran** [comment]
Here’s some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

**Comment by kishorepran** [comment]
Here’s some useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/
CC: @mpdifran

**Comment by mpdifran** [comment]
cc'ing @maxim-chipeev as well!

**Comment by zarghol** [comment]
Hello, as the deadline for compliance is fixed as the May 1st, is there any updates on this subject ?
Thanks !

**Comment by iharkatkavets** [comment]
Hey, any updates guys?

**Comment by maxim-chipeev** [comment]
Hi, definitely will be taking a look very soon at this!

**Comment by kishorepran** [comment]
Check with this tool as well. Swinject is not using any required reason API.
https://github.com/omarzl/ios_17_required_reason_api_scanner/tree/binary_analyzer
@FONickReichard  : you can close this issue safely
