### ISSUE TITLE
Not building on visionOS

### ISSUE THREAD

**Issue by rafaelvda** [Swinject/Swinject#543]
Hello

I'm trying to build my existing app for VisionPro (simulator). But I encounter an error during the build:
"could not find module 'Swinject' for target 'x86_64-apple-ios-simulator'; found: arm64-ios-simulator at <path>"

Do you have any ideas to resolve my bug ?

(I'm working on Xcode 15.2 beta)

Thanks everyone :)

<img width="596" alt="Capture d’écran 2023-12-22 à 15 02 35" src="https://github.com/Swinject/Swinject/assets/61911915/c5d74e11-cbd4-4897-afb5-7a260f260cae">

**Comment by maxim-chipeev** [comment]
Hi Rafael, I think it will be addressed in release 2.8.5 which will come soon.
