### ISSUE TITLE
Not able to install the latest version 2.8.4 via cocoapods

### ISSUE THREAD

**Issue by kishorepran** [Swinject/Swinject#548]
Hello Team,
Seems like the update version 2.8.4 was not pushed to cocoa pods trunk.
Searching on cocoa pods trunk shows last version as 2.8.3
Request to please push the 2.8.4 update to trunk if not done already.
Thanks

Reference link:
https://github.com/CocoaPods/Specs/tree/master/Specs/3/0/d/Swinject
https://cocoapods.org/pods/Swinject
CC: @mpdifran

**Comment by mpdifran** [comment]
cc @maxim-chipeev

**Comment by kishorepran** [comment]
Hi @mpdifran , if you don't mind, may I get collaborator access in GitHub and Cocoa-pods.
I have deployed 2 pods successfully. I am more than curious to debug and fix this issue + start working on closing / resolving existing issues.

CC: @maxim-chipeev

**Comment by maxim-chipeev** [comment]
Hi @kishorepran, thank you for creating the issue. Please try again I have deployed 2.8.4. 🎉
