### ISSUE TITLE
Compilation issue with the latest version of 2.8.5

### ISSUE THREAD

**Issue by lancefu-eventbase** [Swinject/Swinject#553]
After running update in our projects, we noticed Swinject has been updated to 2.8.5, but the project fails to compile.

There seems to be issues with how conflicts were resolved in the xcodeproj file. The header file was removed, but it remained in the project file. However, the ThreadSafeDictionary.swift and ReadWriteLock.swift weren't added. After adding them back and removing the header file, the project will compile.

<img width="1798" alt="Screenshot 2024-04-08 at 11 25 04 AM" src="https://github.com/Swinject/Swinject/assets/160959363/af4ba582-6fa8-4f3c-94d9-009c9e569de5">

**Comment by lancefu-eventbase** [comment]
Thank you @maxim-chipeev for resolving it. Looks like patch has been deployed. The new tag v.2.8.2 has the fix.
I will close the issue now.

**Comment by maxim-chipeev** [comment]
No problem, thanks for posting this issue!
