### ISSUE TITLE
Better explanation of ObjectScope.Graph in docs

### ISSUE THREAD

**Issue by roosmaa** [Swinject/Swinject#56]
I find the description of the .Graph scope slightly lacking. It doesn't really communicate well how this factory method reuse would work. For me the best way to drive the point across would be with an example I guess.

I'm currently guessing that the .Graph scope works as follows. Lets say there is the following dependency graph:

- MyCoolService depends on OtherService and Logger
- OtherService depends on Logger
- Logger has no dependencies

Now, if I were to resolve MyCoolService, it's factory would resolve OtherService first, which in turn initialises the Logger. Now back in MyCoolService factory, since the Logger has already been initialised the same instance is returned. Effectively `coolService.otherService.logger === coolService.logger`.

Is this correct?

**Comment by yoichitgy** [comment]
Hi @roosmaa. Yes, the understanding is correct. It would be appreciated if you suggest a better description about `.Graph` scope. Thanks.

**Comment by yoichitgy** [comment]
Please feel free to reopen this issue if you have an idea to improve the description!
