### ISSUE TITLE
Issue when resolving with arguments in the test bundle

### ISSUE THREAD

**Issue by baek-jinoo** [Swinject/Swinject#57]
In Xcode 7.2 iOS project v1.0.0, I am having trouble resolving an object with three arguments. The first argument is a struct, and the other two are [Int]s. ```let game = appContainer.resolve(Game.self, arguments: (size, first, second))!``` works in the AppDelegate, but does not work in an XCTest run in the test bundle.

This is how I'm registering:

        container.register(Game.self) { _, size, first, second in
            return Game(boardSize: size,
                first: first,
                second: second
            )
        }

This is the error that I get: ```fatal error: unexpectedly found nil while unwrapping an Optional value```
Please advise.

**Comment by yoichitgy** [comment]
I can't see the cause of the problem from the limited code, but you might be able to find a clue if you check the types of `size`, `first` and `second` parameters because the types are not inferred by the Swift compiler, the container cannot resolve the registered type correctly.

**Comment by yoichitgy** [comment]
If you share your project to anywhere, I can check it.

**Comment by yoichitgy** [comment]
Did you solve the problem? Please feel free to reopen this issue if you need help.

**Comment by baek-jinoo** [comment]
I think I made a mistake when I posted the issue. I tried it again now, and it seems to work. Thanks for the comments and sorry that it took me a while to get back to this.

**Comment by yoichitgy** [comment]
😉
