### ISSUE TITLE
Use reflection for auto-injections?

### ISSUE THREAD

**Issue by Sega-Zero** [Swinject/Swinject#59]
In Typhoon we can mark a property as [auto-injectable](https://github.com/appsquickly/Typhoon/wiki/Auto-injection-%28Objective-C%29), but it works for Objective-C only. 
I think Swinject could use the power of Mirror type [[1]](http://appventure.me/2015/10/24/swift-reflection-api-what-you-can-do/), [[2]](http://nshipster.com/mirrortype/) to find properties we can automatically resolve.
I think of UIViewControllers and SwinjectStoryboard enhancement, so we could get rid of `setup` extension method in favour of the code like this (I tried to patсh SwinjectStoryboard class):
```swift
private func injectDependency(viewController: UIViewController) {
        //get the reflection info
        let mirror = Mirror(reflecting: viewController)
        //enumerate properties
        for case let (label?, anyValue) in mirror.children {
            let propMirror = Mirror(reflecting: anyValue)
            //I couldn't find a better way to detect auto-injectable properties =) 
            if label.substringToIndex(label.startIndex.advancedBy(6, limit: label.endIndex)) == "inject" {
                //in here we could use propMirror.subjectType as dynamicType to find the type to be instantiated
               //I tried to register this var with registerForStoryboard with no success, maybe you could help here?:
               //Cannot invoke 'resolve' with an argument list of type '(Any.Type)'
                SwinjectStoryboard.defaultContainer.registerForStoryboard(viewController.dynamicType, initCompleted: { r, c in
                    viewController.setValue(r.resolve(propMirror.subjectType), forKey: label)
                })
            }
        }

        let registrationName = viewController.swinjectRegistrationName
        container.runInitCompleted(viewController.dynamicType, controller: viewController, name: registrationName)

        for child in viewController.childViewControllers {
            injectDependency(child)
        }
    }
```

If we could solve resolving from mirror.subjectType, then we can later have dynamic property in ViewController like this:
```swift
dynamic var injectWeatherFetcher: WeatherFetcher?
```
`dynamic var` is important part - `setValue` works with `@objc` or `dynamic` vars.

What do you think?

**Comment by yoichitgy** [comment]
Thanks @Sega-Zero for the nice idea. I also read the article [[1]](http://appventure.me/2015/10/24/swift-reflection-api-what-you-can-do/) about `Mirror`. It's interesting to use `Mirror` for the reflection.

One thing I care is I would like to keep the current usage of `SwinjectStoryboard` to explicitly define dependencies. Typhoon says ["Use Auto-injection"](https://github.com/appsquickly/Typhoon/wiki/Auto-injection-%28Objective-C%29#use-auto-injection---) and ["Don't use Auto-injection"](https://github.com/appsquickly/Typhoon/wiki/Auto-injection-%28Objective-C%29#dont-use-auto-injection--), and I prefer the latter idea because decoupling of components (including Swinject itself) is the key idea of dependency injection.

> ## Don't use Auto-injection . .
> - When you wish to avoid coupling your class to any Typhoon APIs. Define injections in a TyphoonAssembly instead.
> - When you wish to document an applications assembly in a centralized fashion.

Anyway, I'm planning to move `SwinjectStoryboard` from `Swinject` repo to a new repo as I told in PR #58, so implementing the auto injection storyboard in another repo looks good to support the auto injection one and the current `SwinjectStoryboard`.

Are you interested in implementing auto injection in another repo?

**Comment by Sega-Zero** [comment]
I don't like implicit injection too, but in case of storyboards, it is pretty hard to pass dependencies across all the scenes. `prepareForSegue` is the best place for passing injections, but I don't like the fact, that the scene owner have to get more dependencies than it needs to pass them to child scenes. Some kind of ServiceLocator would simplify the life of developers in a big projects with several storyboards and a huge amount of scenes. 

I also have another thoughts on simplifying injections. I like the concept of Protocol-Oriented Programming in swift2. Maybe swinject could have a protocols that might be used both explicitly and implicitly, something like this:
```swift
// protocol for storing several containers (one container to rule them all is worse then several containers, each for a separate group of classes)
public protocol ResolvableCollection {
    var containers: [Resolvable] { get }
}
public protocol Injectable {
    func injectDependencies(fromResolvable resolvable: Resolvable)
}
```

So, view controllers could hold `Resolvable`'s (that will be injected too) and form injection in `prepareForSegue` manually. Or, if the developers agrees with implicit injections, he would import a separate module with storyboard swizzling in SwinjectStoryboard and `prepareForSegue` swizzling. Something like that:
```swift
//auto stuff
extension UIViewController {
    public override class func initialize() {
        struct Static {
            static var token: dispatch_once_t = 0
        }
        dispatch_once(&Static.token) {
            let original = class_getClassMethod(UIStoryboard.self, "prepareForSegue:sender:")
            let swizzled = class_getClassMethod(UIStoryboard.self, "swinject_prepareForSegue:sender:")
            method_exchangeImplementations(original, swizzled)
        }
    }

    @objc
    private class func swinject_prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let collection = self as? ResolvableCollection, let injectableVC = segue.destinationViewController as? Injectable {
            collection.containers.forEach {
                injectableVC.injectDependencies(fromResolvable: $0)
            }
        }
        self.swinject_prepareForSegue(segue, sender: sender)
    }
}

extension Injectable where Self: UIViewController {
    public func injectDependencies(fromContainer container: Container) {
//Mirror stuff
    }
}
```
After that, developer will need to add `Injectable` conformance to the destination viewcontrollers and `ResolvableCollection` conformance to the source viewcontrollers. Plus, some auto-injectable naming conventions if using `MirrorType` stuff. 
The description is a little bit fuzzy, I'm still thinking on a better implementation =)

------------------------- 

As for separate repo - I think it is better to keep everything it in this repo. You can move auto-inject/storyboard stuff to a separate pod subspecs in your `podspec` and make it optional. So all the sources could be in sync with the rest of code. If anyone needs it - he will include the subspec in Podfile.

**Comment by yoichitgy** [comment]
@Sega-Zero thanks for your great idea💡My concern is just keeping the current explicit SwinjectStoryboard. So, coexisting of the explicit one and implicit (auto-inject) one is ok like Typhoon does.

I'll read your idea again deeply after I release Swinject v1.1.0.

---

I want to provide Swinject to server-side (Linux) programming, and to support [Swift Package Manager, Carthage and CocoaPods](https://speakerdeck.com/neonichu/swift-package-manager?slide=50). I tried to support SPM with SwinjectStoryboard in this single repo as #48 using SPM's target directories, but it was actually difficult for Swift limitation (same file names are not allowed) and usage of Objective-C code. So, I've planned to put the iOS/OSX/tvOS/watchOS specific items to another repo.

(Thanks for telling me about subspecs of CocoaPods. I didn't know about it.)

**Comment by yoichitgy** [comment]
@Sega-Zero, it's a nice idea to use `prepareForSegue` as a hook to inject dependencies💡 Also it's interesting to take advantage of protocol extensions.

My concern about `ResolvableCollection` protocol is we have to pass `Container`s to a lot of `UIViewController`s. So, I guess the best solution would be something between your 1st idea (original comment) and 2nd idea (using protocol extensions).

I would like to add the implicit storyboard feature to v2.0.0. We can develop the idea in this issue, then we can move to implementation.

**Comment by yoichitgy** [comment]
Another idea, inspired by your idea, is subclassing `UIStoryboardSegue` and overriding `perform` method, or swizzling it, though I'm still not sure whether this is good.

**Comment by Sega-Zero** [comment]
One thing I'm aware of is root scenes on storyboards - there is no prepareForSegue call for them, but only instantiate one.

**Comment by yoichitgy** [comment]
@Sega-Zero yes, you pointed out the good point. It looks we shouldn't depend on Segues to implement the Storyboard feature.

**Comment by Sega-Zero** [comment]
Another great idea came into my head =)
We can add more explicitness for reflection. Declare a protocol that has a method, that returns injectable properties names and, while enumerating, inject those one that match:

```swft
public protocol AutoInjectable {
    func injectable() -> Set<String>
}

...

if let autoInjectable = viewController, let injectablePropertyNames = autoInjectable.injectable() {
    let mirror = Mirror(reflecting: viewController)
    //enumerate properties
    for case let (label?, anyValue) in mirror.children {
        let propMirror = Mirror(reflecting: anyValue)
        if injectablePropertyNames.contains(label) {
           //resolve property with propMirror.subjectType + setValue
           viewController.setValue(label, container.resolve(propMirror.subjectType)
        }
   }
```

What do you think?

**Comment by yoichitgy** [comment]
@Sega-Zero it looks much better! Would you give me an example how to use the auto injection? I would like to make sure and remove misunderstanding😃

**Comment by Sega-Zero** [comment]
Sure. Imagine we have a way to catch a moment a viewcontroller is to be created. SwinjectStoryboard, prepareForSegue, whatever. And you are about to inject the dependencies.
Now, a viewController looks like this:
```swift
class WeatherTableViewController: UITableViewController, AutoInjectable {
    var weatherFetcher: WeatherFetcher?
    private var cities = [City]() {
        didSet {
            tableView.reloadData()
        }
    }
    func injectable() -> Set<String> {
        return ["weatherFetcher", "cities"]
    }
    override func viewWillAppear(animated: Bool) {
...
```
Now we know what properties names we should take into consideration while enumerating with `Mirror`. No need in registering viewcontroller in SwinjectStoryboard container at all, every dependency comes automatically, but with explicit list of injectable properties.
What's great about this is that a developer can make own rules of auto-injection with protocol extension:
```swift
extension AutoInjectable where Self: UIViewController {
    func injectable() -> Set<String> {
        return ["weatherFetcher", "cities"]
    }
}
```
Now any viewcontroller that contains `weatherFetcher` and `cities`  will be injected automatically. Or we could change the code a little bit so the developer maybe could return a closure, or start phrase (like in the first idea, any property that starts with "inject") to match properties by mask for all viewcontrollers.

____

Also, I still think `prepareForSegue` is the best place for injections. It is is designed to be swizzled =) As for the root scenes, `viewDidLoad`/`awakeFromNib` swizzling may be a possible candidate.

**Comment by yoichitgy** [comment]
Thanks @Sega-Zero. I'll reply shortly.

**Comment by yoichitgy** [comment]
@Sega-Zero, I think the `AutoInjectable` protocol is the best way to achieve the auto injection in the current specification of Swift language😃

I studied auto injection, and if Swift supports custom attribute, marking auto injectable protocols with `@inject` like Dagger looks good, but still it is not supported by Swift.

```swift
class WeatherTableViewController: UITableViewController {
    @inject var weatherFetcher: WeatherFetcher?
}
```

One concern to specify property names with strings is it is not safe if you change a property name for refactoring. In that case, you have to change the string name returned by `injectable()` method too to match the modified property name.

Do you think there is a way to generate compilation error if a property specified by `injectable` string does not exist? Or maybe it's better to provide a script to check the property existence and add instruction to run the script in a `Run Script` phase of an Xcode target.

**Comment by Sega-Zero** [comment]
I've never seen anyone did this other way than build phase. I think `Run script` phase is the only way we could produce the warnings. I like how this is done in [swiftlint](https://github.com/realm/SwiftLint), we could provide a tool that checks all AutoInjectables for matching names in the same way.

**Comment by yoichitgy** [comment]
@Sega-Zero, yes, it is a good example to generate warnings❗️ So, it looks we can implement the feature with the warning generation. Another thing I noticed is circular dependencies. Do you think circular dependencies can be resolved with the auto injection? (I'm sorry for the nitpicking again.)

**Comment by Sega-Zero** [comment]
I'm not sure about circular dependencies (I never actually need one =)), but I think they can be resolved since we know the type of a variable

**Comment by yoichitgy** [comment]
We can investigate the circular dependencies when we develop a prototype. Will you develop it in your repo?

**Comment by Sega-Zero** [comment]
Yeah, I can make an outline of AutoInjectable stuff, then we could sum our efforts to reach the best results =)

**Comment by yoichitgy** [comment]
👍

**Comment by Sega-Zero** [comment]
My first approach failed =) `dynamic` vars enforce us to use ObjC classes, which is not good, and without it, `setValue` is not working. My colleague pointed me to a [very interesting approach in Dip](https://github.com/AliSoftware/Dip/blob/develop/Sources/AutoInjection.swift#L30). Maybe we could do the same way?

**Comment by yoichitgy** [comment]
I also tried `setValue` without `NSObject` inheritance and didn't work as you said.

For now, we need to use boxing (or wrapping) like Dip or Typhoon as you said. When Swift supports custom attributes in the future, we can migrate from boxing to `@inject` attribute like Dagger or Guice in Java.

So, let's try the boxing for our auto injection.

**Comment by dcunited001** [comment]
bummer, i'm trying to get auto-injection to work at the moment.  i didn't realize that's what i was doing, but it seems really cool.

**Comment by yoichitgy** [comment]
Feel free to tell us if you get a good idea to implement the auto-injection👍

**Comment by dcunited001** [comment]
@yoichitgy Lately I've been looking into swift's reflection faculties, but I doubt I'll think of anything that hasn't been tried yet.  I love your work on Swinject so far though.  This library's awesome!

Also, I'm a bit wary of auto-injection, since I'm allowing users to parse XML and define their own methods for parsing XML.

**Comment by yoichitgy** [comment]
@dcunited001 thank you for your kind message. Auto-injection is optional. You can use the current explicit injection too. You can use either of them depending on your situation.

**Comment by yoichitgy** [comment]
I'm going to close this issue in Swinject project. @Sega-Zero I'll create a new repository for auto injection in [Swinject Group](https://github.com/Swinject). Feel free to tell me if you are still interested.

**Comment by Sega-Zero** [comment]
I don't really have free time for it now, but I'm still interested.

**Comment by yoichitgy** [comment]
Ok, please feel free to notify me anytime when you want to restart it😃

**Comment by Sega-Zero** [comment]
Sure. I think I'll have a ready pull request by this time :)
