### ISSUE TITLE
registerForStoryboard doesn't work with multiple storyboard

### ISSUE THREAD

**Issue by luannguyenkhoa** [Swinject/Swinject#6]
```swift
// ViewController1 in Mail.storyboard
container.registerForStoryboard(ViewController1.self) { r, c in
     c.viewModel = r.resolve(ViewModeling1.self)!              // 1
}
// ViewController2 in Other.storyboard
container.registerForStoryboard(ViewController2.self) { r, c in
    c.viewModel = r.resolve(ViewModeling2.self)!              // 2
}
// in didFinishLaunchingWithOptions
let storyboard = SwinjectStoryboard.create(name: "Main", bundle: bundle, container: container)
```
closure 1 is called when push to viewcontroller1, but not with closure 2
How to i resolve this issue ?

**Comment by yoichitgy** [comment]
If `ViewController2` is in `Other.storyboard`, another storyboard instance should be created:

```swift
let mainStoryboard = SwinjectStoryboard.create(name: "Main", bundle: bundle, container: container)
let otherStoryboard = SwinjectStoryboard.create(name: "Other", bundle: bundle, container: container)
```

**Comment by luannguyenkhoa** [comment]
thanks for your prompt response

//  didFinishLaunchingWithOptions method in AppDelegate class
let bundle = NSBundle(identifier: "rootViewController")
let mainStoryboard = SwinjectStoryboard.create(name: "Main", bundle: bundle, container: container)
let otherStoryboard = SwinjectStoryboard.create(name: "Other", bundle: bundle, container: container)
window.rootViewController = storyboard.instantiateInitialViewController()
return true

it still does not work. which object should the otherStoryboard assigns to ?

**Comment by yoichitgy** [comment]
Are you using [Storyboard Reference](http://code.tutsplus.com/tutorials/ios-9-staying-organized-with-storyboard-references--cms-24226) to transit from the control in Main.storyboard to the other in Other.storyboard? If not, tell me how you use the storyboards and view controllers?

**Comment by luannguyenkhoa** [comment]
yes, i'm using Storyboard Reference. 
Anw, i resolved this issue with the code below
window.rootViewController = otherStoryboard.instantiateInitialViewController()
window.rootViewController = mainStoryboard.instantiateInitialViewController()

is it bad solution ?

**Comment by yoichitgy** [comment]
Storyboard Reference is not supported yet. I added Issue #8 to track the feature.

So far, a workaround is putting all the view controllers in a single storyboard. Thank you for posting this issue. It is helpful for me to understand how users want to use Swinject.

**Comment by yoichitgy** [comment]
Swinject version 0.3 supports Storyboard References.

**Comment by luannguyenkhoa** [comment]
Sound great.
Thanks a lot.
