### ISSUE TITLE
Arguments forwarding to resolver's initCompleted

### ISSUE THREAD

**Issue by nayzak** [Swinject/Swinject#64]
Here demonstration of what I want to do: 
```swift
container.register(MenuPageModeller.self) {  r, menuId in MenuPageModel(menuId: menuId) }

container.register(MenuPage.self) { _ in MenuPage() }
      .initCompleted { r, page in
        page.viewModel = r.resolve(MenuPageModeller.self, argument: /* ??? */)
      }
```

Is there a way to do that? Or I need another approach?

**Comment by yoichitgy** [comment]
You can do that if I caught your question correctly.

Here is the document:
https://github.com/Swinject/Swinject/blob/master/Documentation/DIContainer.md#registration-with-arguments-to-di-container

**Comment by nayzak** [comment]
In documentation nothing mentioned about parameters and `initCompleted` callback. In my case I have a view model, that depends on some parameters and services. So I registering it like this:
```swift
container.register(MenuPageModeller.self) {  r, menuId in 
  MenuPageModel(menuId: menuId, apiService: r.resolve(ApiService.self)!) 
}
```
And I have a view controller, that have public property `viewModel: MenuPageModeller`. I'd like to inject this property automatically. Instead of doing this: 
```swift
let viewModel = container.resolve(MenuPageModeller.self, argument: 123)
let page = MenuPage()
page.viewModel = viewModel
```
I'd like to do this:
```swift
let page = container.resolve(MenuPage.self, argument: 123)
```

Is that possible? Or I'm trying to do something weird? I'm new to DI :)

**Comment by yoichitgy** [comment]
You can do that something like this without using `initCompleted` if your types do not have circular dependencies.

```swift
container.register(MenuPageModeller.self) {  r, menuId in MenuPageModel(menuId: menuId) }

container.register(MenuPage.self) { r, menuId in
         let page = MenuPage()
         page.viewModel = r.resolve(MenuPageModeller.self, argument: menuId)
         return page
     }
```

**Comment by nayzak** [comment]
Thanks! I have already tried this example before asking my question, but compiler didn't understand this code:
```swift
container.register(MenuPage.self) { r, menuId in
         let page = MenuPage()
         page.viewModel = r.resolve(MenuPageModeller.self, argument: menuId)
         return page
     }
```

After your answer I tried it again and figured out, that we need to specify closure arguments types:
```swift
container.register(MenuPage.self) { (r: ResolverType, menuId: Int) in
      let page = MenuPage()
      page.viewModel = r.resolve(MenuPageModeller.self, argument: menuId)!
      return page
    }
```
And this works as expected.

Thank you again! :+1:

**Comment by yoichitgy** [comment]
@nayzak that's good to hear you got the solution❗️I forgot mentioning the explicit type specification in case the Swift compiler cannot infer the types.
