### ISSUE TITLE
Building for OSX target fails with CocoaPods

### ISSUE THREAD

**Issue by phonaddicts** [Swinject/Swinject#67]
Swinject does not compile for OSX caused in _SwinjectStoryboardBase.h. Here UIKit and UIStoryboard are referenced. Please advice.

**Comment by yoichitgy** [comment]
What did you use to install Swinject? CocoaPods or Carthage?

**Comment by phonaddicts** [comment]
I've been using CocoaPods.

**Comment by yoichitgy** [comment]
If your target is OSX, Podfile should specify **platform :osx, '10.10'** like this.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.10'
use_frameworks!

pod 'Swinject', '~> 1.1.0'
```

Would you try using this Podfile?

**Comment by phonaddicts** [comment]
First of all many thanks for providing this awesome piece of software.

After changing the Podfile as you recommended and after deleting my Pods directory and executing a pod install everything works like a charm now. Thank you and good luck.

**Comment by yoichitgy** [comment]
Thank you for your feedback😃

I updated the project README to get Podfile instruction clearer for OSX: a588093b8b568ebb99b2501d0b1980fc1e4ab568
