### ISSUE TITLE
Build failure after updating to Xcode 7.3 (7D175)

### ISSUE THREAD

**Issue by robinhayward** [Swinject/Swinject#71]
"Module file was created by an older version of the compiler; rebuild 'Swinject' and try again: "

Any ideas? I have tried `carthage build --platform ios` but no change

**Comment by yoichitgy** [comment]
I'm going to release a new version with a prebuilt framework by Xcode 7.3

**Comment by MartijnSchoemaker** [comment]
If you don't want to use the prebuild framework you can use:
carthage update --no-use-binaries
