### ISSUE TITLE
swift 2.2 warnings

### ISSUE THREAD

**Issue by paulz** [Swinject/Swinject#77]
⚠️  Pods/Swinject/Sources/SwinjectStoryboard/Storyboard+Swizzling.swift:35:66: use '#selector' instead of explicitly constructing a 'Selector'

            let original = class_getClassMethod(Storyboard.self, Selector("storyboardWithName:bundle:"))
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/Storyboard+Swizzling.swift:36:66: use '#selector' instead of explicitly constructing a 'Selector'

            let swizzled = class_getClassMethod(Storyboard.self, Selector("swinject_storyboardWithName:bundle:"))
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/Storyboard+Swizzling.swift:35:66: use '#selector' instead of explicitly constructing a 'Selector'

            let original = class_getClassMethod(Storyboard.self, Selector("storyboardWithName:bundle:"))
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/Storyboard+Swizzling.swift:36:66: use '#selector' instead of explicitly constructing a 'Selector'

            let swizzled = class_getClassMethod(Storyboard.self, Selector("swinject_storyboardWithName:bundle:"))
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▸ Compiling SwinjectStoryboard.swift

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/SwinjectStoryboard.swift:42:54: use '#selector' instead of explicitly constructing a 'Selector'

            if SwinjectStoryboard.respondsToSelector(Selector("setup")) {
                                                     ^~~~~~~~~~~~~~~~~

Thank you for the awesome framework!

We have migrated to swift 2.2 and xcode7.3. This caused the following warnings:

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/SwinjectStoryboard.swift:43:52: use '#selector' instead of explicitly constructing a 'Selector'

                SwinjectStoryboard.performSelector(Selector("setup"))
                                                   ^~~~~~~~~~~~~~~~~

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/SwinjectStoryboard.swift:42:54: use '#selector' instead of explicitly constructing a 'Selector'

            if SwinjectStoryboard.respondsToSelector(Selector("setup")) {
                                                     ^~~~~~~~~~~~~~~~~

⚠️  Pods/Swinject/Sources/SwinjectStoryboard/SwinjectStoryboard.swift:43:52: use '#selector' instead of explicitly constructing a 'Selector'

                SwinjectStoryboard.performSelector(Selector("setup"))
                                                   ^~~~~~~~~~~~~~~~~

Would it be possible to make a release for swift 2.2 without the warnings?

Thank you!

**Comment by yoichitgy** [comment]
It's easy to replace `Selector("storyboardWithName:bundle:")` with `#selector` but not `Selector("setup")`.

I'm investigating a way to do that. Do you have any idea?

**Comment by paulz** [comment]
Currently our build log runs out of space on travis due to this kind of warnings.
We would benefit from the easy fix, even if setup selector is not fixed.

**Comment by yoichitgy** [comment]
Thank you for explaining your situation. I'll fix the warnings, but I want to fix them together. (I want to either get rid of the warnings or keep supporting Swift 2.1. Fixing only `Selector("storyboardWithName:bundle:")` breaks both.)

Until I fix both the selectors, you can fork this repo to patch the easy fix of `Selector("storyboardWithName:bundle:")` in it. I'm 
sorry for the inconvenience😥

**Comment by yoichitgy** [comment]
PR #89 fixes the warnings.
