### ISSUE TITLE
RegisterMultiple and ResolveAll

### ISSUE THREAD

**Issue by mennahmostafa** [Swinject/Swinject#79]
Does Swinject support (or plans to support) ResolveAll and RegisterMultiple as in [TinyIoC](https://github.com/grumpydev/TinyIoC#key-features)?

Thanks!

**Comment by yoichitgy** [comment]
Hi @mennahmostafa😀 Swinject does not support and have plan to support them (though they are technically interesting👍)

I might change my mind if iOS apps have good use cases taking advantage of them.
