### ISSUE TITLE
View Controller injection MVP

### ISSUE THREAD

**Issue by davidosorio** [Swinject/Swinject#81]
Hello there, I am using the pattern MVP in my app, but I have some trouble when I want to set the view to my presenter. 

We can't resolve explicitly the view controllers registered by registerForStoryboard method, so I wonder how to get the view controller when I am registering the presenter, I was thinking about set the view to the presenter in registerForStoryboard method, but I don't know if it is correct. Any help please?

```
let mainContainer: Container = Container() { container in

        container.register(Presenter.self){ r in
            return Presenter()
        }.initCompleted { r,c in
            let view = /* HOW GET THE VIEW */
            c.view = view
        }
        
        container.registerForStoryboard(Test1ViewController.self) { r, c in
            let presenter = r.resolve(Presenter.self)
            c.presenter = presenter
        }
}
```

In AppDelegate:

```
let sb = SwinjectStoryboard.create(name: "Main", bundle: nil, container: self.mainContainer)
let controller = sb.instantiateViewControllerWithIdentifier("Test1View") as! Test1ViewController
```

**Comment by yoichitgy** [comment]
Hi @davidosorio. @Nikita2k's templates might be helpful to do what you want to do:

https://github.com/Nikita2k/SwiftViper

**Comment by Nikita2k** [comment]
In fact, I don't have storyboards (I believe using SB is a bad practice).

But I can suggest to remove `initCompleted` block and pass your view to presenter initialization

**Comment by yoichitgy** [comment]
Hi @Nikita2k, thank you for your help!

(I had misunderstanding about the question. @davidosorio uses `Presenter` but it was not in VIPER, but in MVP, which is more like MVVM.)

**Comment by davidosorio** [comment]
Hi, thank you @Nikita2k, @yoichitgy for your answers, for me, use or no SB depends on the size of the project, I agree that in a large project Storyboards are a bad practise, actually I use one storyboard per module/component.

**Comment by yoichitgy** [comment]
@davidosorio, another approach is here (just for your information):
https://github.com/rizumita/TransitionOperator

I prefer using storyboards except the problem of DI, and trying to keep them small.
I understand advantages of UI implementation without storyboards. So, storyboards can be chosen depending on the size or type of your project, or your preference. (I keep myself neutral in Swinject project.)

Thanks @Nikita2k again for your help and sharing your great practice!
