### ISSUE TITLE
Ability to remove services for a given assembly

### ISSUE THREAD

**Issue by brynjar** [Swinject/Swinject#84]
If I apply assemblies, like so `assembler.applyAssemblies([SomeServicesAssembly()]) `then the movitation for doing this is to be able to group the various services in that assembly together.
Accordingly, I'd like to be able to remove all the services that were registered via that assembly only, as opposed to `container.removeAll()` which is too broad.

So something like `assembler.removeAssemblies([SomeServicesAssembly()])`

**Comment by yoichitgy** [comment]
Hi @brynjar. Thank you for telling me your use case of Swinject. I think removing the container and creating a new container from a different set of assemblies is enough for the case. What do you think about my idea?

**Comment by yoichitgy** [comment]
Feel free to reopen this issue if you get a good idea. Thanks!
