### ISSUE TITLE
Compiling large closures when initializing containers increases build time

### ISSUE THREAD

**Issue by Lutzifer** [Swinject/Swinject#97]
The readme gives 

```
    let container = Container() { c in
        c.register(AnimalType.self) { _ in Cat(name: "Mimi") }
        c.register(PersonType.self) { r in
            PetOwner(pet: r.resolve(AnimalType.self)!)
        }
        c.register(PersonViewController.self) { r in
            let controller = PersonViewController()
            controller.person = r.resolve(PersonType.self)
            return controller
        }
    }
```

as an example how to use the library.

However, doing this with larger numbers of dependencies noticeably slows down compilation, as the closure seems to be parsed every time the appModule is used (e.g. to resolve).
In our app, this amounted to around 42 seconds. (https://gist.github.com/Lutzifer/64c00ddf839b866a81274496fa48de04 contains the script I used to measure)

Making an extension on Container like this:

```
extension Container {
   func registerModules() {
        self.register(AnimalType.self) { _ in Cat(name: "Mimi") }
        self.register(PersonType.self) { r in
            PetOwner(pet: r.resolve(AnimalType.self)!)
        }
        self.register(PersonViewController.self) { r in
            let controller = PersonViewController()
            controller.person = r.resolve(PersonType.self)
            return controller
        }

  }   
}
```

and calling it as 

```
    let container = Container() { c in
       c.registerModules()
    }
```

solved this for us, as the closure does not need to be parsed.

Might be worth noting in the Readme.

**Comment by yoichitgy** [comment]
@Lutzifer thanks for measuring the build time👍 It's a general problem of type inference. Would you measure the build time in your environment with the container explicitly typed as `(c: Container)`?

```swift
let container = Container() { (c: Container) in
    c.register(AnimalType.self) { _ in Cat(name: "Mimi") }
    c.register(PersonType.self) { r in
        PetOwner(pet: r.resolve(AnimalType.self)!)
    }
    c.register(PersonViewController.self) { r in
        let controller = PersonViewController()
        controller.person = r.resolve(PersonType.self)
        return controller
    }
}
```

If it works, I'd like to change the README in that way with some notice about type inference.

**Comment by Lutzifer** [comment]
explicitly typing c did not suffice to fix the additional build time.

**Comment by yoichitgy** [comment]
Thank you for the investigation. It looks good to mention the performance of the convenience initializer in README.

**Comment by yoichitgy** [comment]
The post below might be helpful.

**Comment by PhilippeBoisney** [comment]
Faced the same issue (Build time for Container was approx. ~ 80ms). So I did this:

```
let container = Container() { (container: Container) in
    
    //This line tell the compiler what is the type of "c" variable
    let c: Container = container as Container

    c.register(AnimalType.self) { _ in Cat(name: "Mimi") }
    c.register(PersonType.self) { r in
        PetOwner(pet: r.resolve(AnimalType.self)!)
    }
    c.register(PersonViewController.self) { r in
        let controller = PersonViewController()
        controller.person = r.resolve(PersonType.self)
        return controller
    }
}
```

Compile time for my Container drops to 21ms

**Comment by yoichitgy** [comment]
Thanks @PhilippeBoisney for sharing your experience and the workaround 👍👍👍

**Comment by PhilippeBoisney** [comment]
No problem ;)
