### ISSUE TITLE
Usecase for multiple containers

### ISSUE THREAD

**Issue by jakubvano** [Swinject/Swinject#98]
Original post in #80 

> For a while I was viewing parent - child relationship as strange too, but I grew to like it and now find it useful for managing scopes with different lifetime within application.
> 
> On the other hand, I am probably missing usefulness of having multiple Containers / Assemblers when you only want to keep single reference to the parent - AFAIK at that point it doesn't matter whether services are registered on parent or child, as you can only call resolve() on parent. So why not register them all on parent Container? 
> I'd love if you could clarify this for me.

**Comment by jakubvano** [comment]
To clarify what I mean by scope management:

 I do use multiple containers with parent-child relationship on them when I need some "singletons" (`.inObjectScope(.Hierarchy)`) to be destroyed during application life. (E.g. objects holding user-sensitive data after logout). I that case, I have an `applicationContainer` as a parent of `sessionContainer`. After logout `sessionContainer` is destroyed and re-created on login.

However, I am wondering If there are other usecases for multiple `Container`s, which would maybe benefit from different nature of parent - child relationship than is currently implemented

**Comment by yoichitgy** [comment]
Thanks for creating the issue here. I'll answer shortly😃

**Comment by yoichitgy** [comment]
Container hierarchy is used for lifetime management of singletons as you said. Another example is iTunes app for Mac. It can have something like `applicationContainer`, `MusicContainer`, `IPhoneAppsContainer`, etc to manage memory usage. Another use case is just for grouping, but it might be a preference.
