### ISSUE TITLE
Throwing resolve methods

### ISSUE THREAD

**Issue by jakubvano** [Swinject/Swinject#99]
As there are plans for `2.0`, I thought I would throw in this idea:

When trying to unit test my assemblies, I realized it would be nice to "optionaly" resolve instances, i.e. having `resolve()` return `nil` when type cannot be resolved. Currently it returns `nil` only if there are no registrations for given type, but there is no way to return `nil` if there are no registrations for type's dependencies.

One way to solve this, would be changing `resolve()` behaviour so that instead of returning nil when there is no registration it would throw an error.

```
func resolve<T>(serviceType: T.Type) throws -> T
```

Then in registration closures you could write

```
c.register(PersonType.self) { r in
    PetOwner(pet: try r.resolve(AnimalType.self))
 }
```

I realise that in most cases being able to optionally resolve types is not needed, but I was wondering what do others think about such a change.

Thoughts?

**Comment by yoichitgy** [comment]
Thanks for your idea to improve Swinject 😃

I think `Container` is a kind of `Dictionary` returning nil is enough for non-existing key. Repeating `try` is redundant. I want to keep it simple.

**Comment by jakubvano** [comment]
Ok, I agree that it would be redundant for most usecases.

**Comment by yoichitgy** [comment]
If Swift language doesn't require `try` for every throwing function, the API you proposed is great😉

**Comment by jakubvano** [comment]
Well, if you have multiple throwing functions in one expression, you can move try an the start of expression. i.e:

```
c.register(SomeType.self) { r in
    try SomeImpl(
        dep1: r.resolve(Dependency1),
        dep2: r.resolve(Dependency2)
    )
 }
```
Instead of

c.register(SomeType.self) { r in
    SomeImpl(
        dep1: try r.resolve(Dependency1),
        dep2: try r.resolve(Dependency2)
    )
 }
```
